import {content as legacy,monthGrid} from './views.js?v=20261008-single-plan8';
import {escape as e,button as b,pretty,badge,empty} from './ui.js?v=20261008-single-plan8';
import {weekHtml} from './planning.js?v=20261008-single-plan8';

export const platforms=s=>[...s.socials,...['Instagram','Telegram','VK'].filter(name=>!s.socials.some(x=>x.name.toLowerCase()===name.toLowerCase())).map(name=>({id:'platform:'+name,name}))];
export function selectedPosts(s,u){return s.posts.filter(x=>x.projId===u.projId&&(!u.postSocial||x.social===u.postSocial)&&(x.title+' '+(x.text||'')).toLowerCase().includes(u.query.toLowerCase())&&(!u.postStatus||x.status===u.postStatus)).sort((a,b)=>(a.date||'').localeCompare(b.date||''));}
const edit=x=>b('edit','Изменить','data-type="posts" data-id="'+e(x.id)+'"');
const format=x=>({post:'Пост',stories:'Сторис',video:'Видео'}[x.format]||'Пост');
function meta(s,x){const social=s.socials.find(v=>v.id===x.social),status=s.statuses.find(v=>v.id===x.status);return '<div class="cp-meta"><span>'+e(pretty(x.date))+'</span><span>'+e(social?.name||'Без площадки')+'</span><span>'+format(x)+'</span>'+badge(status?.name||'Без статуса',status?.color)+'</div>';}
function connections(s,x){return [s.shoots.find(v=>v.id===x.shootId),s.portfolio.find(v=>v.id===x.portfolioId)].filter(Boolean).map(v=>'<span class="cp-connection">'+e(v.title||v.name)+'</span>').join('');}
function contextPanel(s,u,projects,p){
 const org=s.orgs.find(x=>x.id===u.orgId),options=(list,current,placeholder,count=false)=>'<option value="" '+(!list.some(x=>x.id===current)?'selected':'')+'>'+placeholder+'</option>'+list.map(x=>'<option value="'+e(x.id)+'" '+(x.id===current?'selected':'')+'>'+e(x.name)+(count?' · '+s.posts.filter(v=>v.projId===x.id).length:'')+'</option>').join('');
 return '<section class="card cp-projects cp-compact-context" aria-label="Организация и проект"><div class="cp-context-row"><label>Организация<select data-control="orgId" aria-label="Организация">'+options(s.orgs,u.orgId,s.orgs.length?'Выберите организацию':'Нет организаций')+'</select></label><label>'+(u.archive?'Проект · архив':'Проект')+'<select data-control="projId" aria-label="Проект" '+(!org||!projects.length?'disabled':'')+'>'+options(projects,u.projId,u.archive?'Выберите архивный проект':projects.length?'Выберите проект':'Нет активных проектов',true)+'</select></label><details class="cp-management"><summary>Управление</summary><div class="cp-management-body"><div class="cp-management-group"><strong>Организация</strong>'+b('add','Создать организацию','data-type="orgs"')+(org?b('edit','Изменить организацию','data-type="orgs" data-id="'+e(org.id)+'"')+b('delete','Удалить организацию','data-type="orgs" data-id="'+e(org.id)+'"','danger'):'')+'</div><div class="cp-management-group"><strong>Проект</strong>'+(org?b('add','Создать проект','data-type="projects"')+b('toggle-archive',u.archive?'Показать активные проекты':'Показать архив'):'<p class="muted">Сначала создайте или выберите организацию.</p>')+(p?b('edit','Изменить проект','data-type="projects" data-id="'+e(p.id)+'"')+b('archive',p.archived?'Восстановить проект':'Переместить в архив','data-id="'+e(p.id)+'"')+b('delete','Удалить проект','data-type="projects" data-id="'+e(p.id)+'"','danger'):'')+'</div></div></details></div></section>';
}
function scripts(s,rows){return ['ready','missing'].map(group=>{const list=rows.filter(x=>Boolean(x.text?.trim())===(group==='ready'));return '<section class="cp-script-group"><h2>'+(group==='ready'?'Со сценарием':'Без сценария')+' <span class="cp-count">'+list.length+'</span></h2>'+(list.length?list.map(x=>'<article class="cp-script '+group+'"><div class="cp-script-head"><h3>'+e(x.title)+'</h3>'+edit(x)+'</div>'+meta(s,x)+connections(s,x)+(group==='ready'?'<pre class="cp-script-text">'+e(x.text)+'</pre><div class="cp-card-actions">'+b('copy-script','Копировать текст','data-id="'+e(x.id)+'"','primary')+'</div>':'<p class="muted">'+(x.format==='video'?'Добавьте план видео.':'Добавьте текст публикации.')+'</p>'+b('edit','Добавить сценарий','data-type="posts" data-id="'+e(x.id)+'"','primary'))+'</article>').join(''):'<p class="cp-group-empty">'+(group==='ready'?'Здесь появятся публикации с текстом.':'У всех выбранных публикаций есть сценарий.')+'</p>')+'</section>';}).join('');}
export function content(s,u){
 const projects=s.projects.filter(x=>x.orgId===u.orgId&&Boolean(x.archived)===u.archive),p=projects.find(x=>x.id===u.projId),rows=selectedPosts(s,u);
 let h='<div class="cp-top">'+b('add','＋ Добавить публикацию','data-type="posts" '+(!p?'disabled':''),'primary')+'</div>'+contextPanel(s,u,projects,p);
 if(!p)return h+'<section class="card cp-context-empty">'+empty(!u.orgId?'Выберите или создайте организацию':u.archive?'Выберите проект из архива':'Выберите или создайте проект','Публикации, сценарии и вложения будут собраны в одном проекте.')+(u.orgId?b('add','＋ Создать проект','data-type="projects"','primary'):b('add','＋ Создать организацию','data-type="orgs"','primary'))+'</section>';
 h+=weekHtml(s,u);
 h+='<div class="cp-platforms" aria-label="Площадки">'+b('content-social','Все площадки','data-social="" aria-pressed="'+(!u.postSocial)+'"',!u.postSocial?'active':'')+platforms(s).map(x=>b('content-social',e(x.name)+' <span class="cp-count">'+s.posts.filter(v=>v.projId===p.id&&v.social===x.id).length+'</span>','data-social="'+e(x.id)+'" aria-pressed="'+(u.postSocial===x.id)+'"',u.postSocial===x.id?'active':'')).join('')+'</div><div class="cp-modes" aria-label="Режим публикаций">'+[['cal','▦','Календарь'],['table','▤','Таблица'],['scripts','▧','Сценарии']].map(([v,i,t])=>b('post-tab','<span aria-hidden="true">'+i+'</span> '+t,'data-tab="'+v+'" aria-pressed="'+(u.postTab===v)+'"',u.postTab===v?'active':'')).join('')+'</div><div class="cp-filters"><input data-control="query" value="'+e(u.query)+'" placeholder="Найти публикацию…" aria-label="Поиск публикаций"><select data-control="postStatus" aria-label="Статус"><option value="">Все статусы</option>'+s.statuses.map(x=>'<option value="'+e(x.id)+'" '+(x.id===u.postStatus?'selected':'')+'>'+e(x.name)+'</option>').join('')+'</select><span class="muted">Публикаций: '+rows.length+'</span></div>';
 if(u.postTab==='cal'){const d=new Date(u.postDate+'T12:00');h+='<section class="card cp-calendar"><div class="calendar-head"><div class="calendar-nav">'+b('post-prev','‹','aria-label="Предыдущий месяц"')+'<h2>'+d.toLocaleDateString('ru-RU',{month:'long',year:'numeric'})+'</h2>'+b('post-next','›','aria-label="Следующий месяц"')+'</div>'+b('post-today','Текущий месяц')+'</div><div class="cp-month-grid">'+monthGrid(s,d,false,rows)+'</div><div class="cp-mobile-agenda">'+rows.filter(x=>x.date?.slice(0,7)===u.postDate.slice(0,7)).map(x=>'<article class="cp-agenda-item"><strong>'+e(x.title)+'</strong>'+meta(s,x)+edit(x)+'</article>').join('')+'</div></section>';}
 if(u.postTab==='table')h+='<section class="card">'+(rows.length?'<div class="table-wrap cp-table"><table><thead><tr><th>Тема</th><th>Площадка / формат</th><th>Дата</th><th>Статус</th><th>Рубрика</th><th></th></tr></thead><tbody>'+rows.map(x=>{const status=s.statuses.find(v=>v.id===x.status),rubric=s.rubrics.find(v=>v.id===x.rubric);return '<tr><td data-label="Тема"><strong>'+e(x.title)+'</strong>'+connections(s,x)+'</td><td data-label="Площадка">'+e(s.socials.find(v=>v.id===x.social)?.name||'—')+'<small>'+format(x)+'</small></td><td data-label="Дата">'+pretty(x.date)+'</td><td data-label="Статус">'+badge(status?.name||'Без статуса',status?.color)+'</td><td data-label="Рубрика">'+e(rubric?.name||'—')+'</td><td>'+edit(x)+b('delete','Удалить','data-type="posts" data-id="'+e(x.id)+'"','danger')+'</td></tr>';}).join('')+'</tbody></table></div>':empty('Публикаций не найдено','Измените фильтры или добавьте публикацию.'))+'</section>';
 if(u.postTab==='scripts')h+='<section class="card cp-scripts">'+scripts(s,rows)+'</section>';
 h+='<div class="cp-resources">'+[['links','Ссылки проекта'],['files','Файлы проекта']].map(([v,t])=>b('post-tab',t,'data-tab="'+v+'" aria-pressed="'+(u.postTab===v)+'"',u.postTab===v?'active':'')).join('')+'</div>';
 if(['links','files'].includes(u.postTab)){const old=legacy(s,u);h+=old.slice(old.indexOf(u.postTab==='links'?'<section class="card"><div class="card-header"><h2>Ссылки проекта':'<section class="card"><div class="card-header"><h2>Файлы проекта'));}
 return h;
}
