import {escape as e,button as b,badge} from './ui.js?v=20261008-single-plan8';
import {editor} from './planner-view.js?v=20261008-single-plan8';
import {moscowDate,addDays} from './planner-model.js?v=20261008-single-plan8';
import {scope,owner,scopeFolders,scopeTopics,folderTopics,tableRows} from './folder-model.js?v=20261008-single-plan8';
const date=d=>d?new Date(d+'T12:00Z').toLocaleDateString('ru-RU',{day:'numeric',month:'short',year:'numeric',timeZone:'Europe/Moscow'}):'Без даты';
const boardImage=(s,x)=>{const file=s.files.find(f=>f.id===x.storyboardFileId);return file&&/^data:image\/(png|jpeg|webp|gif|avif);base64,/.test(file.data||'')?'<img class="table-storyboard" src="'+e(file.data)+'" alt="'+e(file.name)+'">':'';};
export function view(s,u){
 if(u.draft)return '<main class="material-page"><div id="topic-editor">'+editor(s,u)+'</div></main>';
 const folders=scopeFolders(s,u),topics=folderTopics(s,u),project=s.projects.find(x=>x.id===u.projId),org=s.orgs.find(x=>x.id===u.orgId),rows=tableRows(s,u),isOrg=scope(u)==='org',owners=isOrg?s.orgs:s.projects.filter(x=>Boolean(x.archived)===u.archive),current=isOrg?org:project,currentFolder=folders.find(f=>f.id===u.folderId);
 let h='<header class="app-header"><div class="app-brand"><span class="brand-symbol">▤</span><strong>Контент-планер</strong></div><div class="header-actions">'+b('export','Экспорт')+'<label class="upload-button">Импорт<input type="file" id="planner-import" accept=".json,application/json"></label></div></header><main class="planner-main"><nav class="main-tabs scope-tabs" aria-label="Проекты и организации">'+[['projects','Проекты'],['organizations','Организации']].map(([v,label])=>b('scope-tab',label,'data-scope="'+v+'" aria-pressed="'+(u.navScope===v)+'"',u.navScope===v?'active':'')).join('')+'</nav><div class="folder-context"><label class="field">'+(isOrg?'Организация':'Проект')+'<select data-select="'+(isOrg?'orgId':'projId')+'" aria-label="'+(isOrg?'Организация':'Проект')+'"><option value="">Выберите '+(isOrg?'организацию':'проект')+'</option>'+owners.map(x=>'<option value="'+e(x.id)+'" '+(x.id===current?.id?'selected':'')+'>'+e(x.name)+(isOrg?'':' · '+e(s.orgs.find(o=>o.id===x.orgId)?.name||''))+'</option>').join('')+'</select></label><details class="management"><summary>Управление</summary><div class="management-menu">'+b('org-create','Создать организацию')+(org?b('org-edit','Изменить организацию')+b('project-create','Создать проект')+b('archive-list',u.archive?'Активные проекты':'Архив проектов'):'')+(project?b('project-edit','Изменить проект')+b('project-archive',project.archived?'Восстановить проект':'В архив')+b('works','Работы проекта'):'')+'</div></details></div>';
 if(!current)return h+'<section class="empty-panel"><h1>'+(isOrg?'Организации':'Проекты')+'</h1><p>Выберите '+(isOrg?'организацию':'проект')+' или создайте новую запись. Внутри будут папки с темами.</p>'+b(org&&!isOrg?'project-create':'org-create',org&&!isOrg?'Создать проект':'Создать организацию','','primary')+'</section></main>';
 h+='<div class="folder-layout"><aside class="folders-panel"><div class="folders-heading"><h2>Папки</h2>'+b('folder-create','＋','aria-label="Создать папку"')+'</div>'+b('folder-open','▱ Без папки <span>'+folderTopics(s,{...u,folderId:''}).length+'</span>','data-id="" aria-pressed="'+(!u.folderId)+'"',!u.folderId?'folder-link active':'folder-link')+folders.map(f=>b('folder-open','▱ '+e(f.name)+' <span>'+scopeTopics(s,u).filter(t=>(t.folderIds||[]).includes(f.id)).length+'</span>','data-id="'+e(f.id)+'" aria-pressed="'+(f.id===u.folderId)+'"',f.id===u.folderId?'folder-link active':'folder-link')).join('')+'</aside><div class="folder-content"><div class="folder-title"><div><span class="small-note">'+e(current.name)+'</span><h1>'+e(currentFolder?.name||'Без папки')+'</h1></div><div class="folder-actions">'+(currentFolder?b('folder-edit','Название','data-id="'+e(currentFolder.id)+'"')+b('folder-delete','Удалить папку','data-id="'+e(currentFolder.id)+'"','danger'):'')+b('topic-create','＋ Тема','','primary')+'</div></div>';
 if(isOrg&&s.projects.filter(x=>x.orgId===u.orgId&&!x.archived).length>1)h+='<label class="field creation-project">Проект для новых тем<select data-select="creation-project">'+s.projects.filter(x=>x.orgId===u.orgId&&!x.archived).map(x=>'<option value="'+e(x.id)+'" '+(x.id===u.projId?'selected':'')+'>'+e(x.name)+'</option>').join('')+'</select></label>';
 const today=moscowDate(),end=addDays(today,6),allRows=tableRows(s,{...u,folderId:u.folderId});
 const events=allRows.flatMap(r=>r.scene?.deadline?[r,{...r,id:r.id+'-deadline',kind:'Крайний срок',date:r.scene.deadline}]:[r]).filter(r=>r.date&&r.date<=end&&!(r.scene?.filmed)&&r.status!=='Опубликовано').sort((a,b)=>a.date.localeCompare(b.date));
 h+='<section class="agenda"><div class="section-heading"><div><span class="eyebrow">БЛИЖАЙШИЕ 7 ДНЕЙ</span><h2>В фокусе</h2></div><span class="small-note">'+date(today)+' — '+date(end)+'</span></div><div class="agenda-grid">'+(events.length?events.map(r=>b('topic-open','<span class="event-kind">'+e(r.kind)+'</span><strong>'+e(r.title)+'</strong><span>'+date(r.date)+'</span><small>'+e(r.channel)+(r.date<today?' · Просрочено':'')+'</small>','data-id="'+e(r.topic.id)+'" data-tab="'+r.tab+'"','agenda-card '+(r.date<today?'overdue':''))).join(''):'<p class="agenda-empty">На ближайшие дни ничего не назначено. Добавьте даты съёмок и публикаций в теме.</p>')+'</div></section><section class="list-surface" id="plan-list"><div class="section-heading"><h2>Темы <span class="count">'+topics.length+'</span></h2><span class="small-note">Одна тема — все съёмки и площадки</span></div><div class="list-tools"><input id="material-search" type="search" aria-label="Поиск тем" placeholder="Найти тему, рубрику или площадку…"><select id="material-filter" aria-label="Готовность темы"><option value="all">Все темы</option><option value="script">Без сценария</option><option value="shoot">Нужно снять</option><option value="approval">Нужны правки</option></select></div><div class="materials-list">'+topics.map(t=>{const dates=[...t.scenes.filter(x=>!x.filmed).map(x=>x.date),...t.variants.filter(x=>x.ready!=='Опубликовано').map(x=>x.date)].filter(Boolean).sort(),rubric=s.rubrics.find(x=>x.id===t.rubric)?.name||'Без рубрики',channels=[...new Set(t.variants.map(v=>v.platform))].filter(Boolean),search=[t.title,rubric,...channels].join(' ').toLowerCase();return '<article class="material-row" data-search="'+e(search)+'" data-script="'+Boolean(t.script?.trim())+'" data-shoot="'+t.scenes.some(x=>!x.filmed)+'" data-approval="'+e(t.approval)+'"><div class="material-info">'+b('topic-open',e(t.title),'data-id="'+e(t.id)+'"','row-open')+'<div class="card-meta"><span>'+e(rubric)+'</span><span>'+e(channels.join(' · ')||'Площадки не выбраны')+'</span>'+(isOrg?'<span>'+e(s.projects.find(p=>p.id===t.projId)?.name||'')+'</span>':'')+'</div></div><div class="material-progress"><span class="'+(!t.script?.trim()?'muted':'')+'">'+(t.script?.trim()?'✓ Сценарий':'○ Сценарий')+'</span><span>'+t.scenes.filter(x=>x.filmed).length+'/'+t.scenes.length+' сцен</span><span>'+t.variants.length+' публикаций</span></div><div class="material-state">'+badge(t.approval||'Не отправлено','#28745b')+'<small>'+date(dates[0])+'</small></div>'+b('topic-open','Открыть →','data-id="'+e(t.id)+'"','open-material')+'</article>';}).join('')+'</div><p id="search-empty" hidden>Нет тем по выбранным условиям.</p>'+(!topics.length?'<div class="empty-state"><h2>Начните с темы</h2><p>В одной карточке будут сценарий, сцены и публикации для всех площадок.</p>'+b('topic-create','＋ Тема','','primary')+'</div>':'')+'</section></div></div></main>';
 return h;
}
