import {questionView} from './qa-scenario.js?v=20261008-topic-only7';
import {speakers} from './scenario-plan.js?v=20261008-topic-only7';
import {storyboardEditor} from './storyboard.js?v=20261008-topic-only7';
import {escape as e,button as b,badge,pretty,field} from './ui.js?v=20261008-topic-only7';
import {scopeFolders} from './folder-model.js?v=20261008-topic-only7';
import {platforms,approval,readiness,plannerState,weekEvents,addDays} from './planner-model.js?v=20261008-topic-only7';
const select=(name,label,value,rows,extra='')=>'<label class="field">'+label+'<select '+extra+' name="'+name+'">'+rows.map(([v,t])=>'<option value="'+e(v)+'" '+(v===value?'selected':'')+'>'+e(t)+'</option>').join('')+'</select></label>';
const optionRows=(rows,empty)=>[['',empty],...rows.map(x=>[x.id,x.name||x.title])];
const quantity=(n,forms)=>n+' '+forms[n%100>=11&&n%100<=14?2:n%10===1?0:n%10>=2&&n%10<=4?1:2];
const dateLabel=date=>date?new Date(date+'T12:00:00Z').toLocaleDateString('ru-RU',{day:'numeric',month:'short',year:'numeric',timeZone:'Europe/Moscow'}):'Не назначена';
const approvalTag=t=>badge(t.approval||'Не отправлено',t.approval==='Согласовано'?'#28745b':t.approval==='Нужны правки'?'#b75c48':'#7054d8');
const open=(t,text)=>b('topic-open',text,'data-id="'+e(t.id)+'"','row-open');
export function view(s,u){
 const p=plannerState(s),orgs=s.orgs,projects=s.projects.filter(x=>x.orgId===u.orgId&&Boolean(x.archived)===u.archive),project=projects.find(x=>x.id===u.projId),topics=p.topics.filter(x=>x.projId===project?.id),org=orgs.find(x=>x.id===u.orgId);
 let h='<header class="app-header"><div class="app-brand"><span class="brand-symbol">▤</span><strong>Контент-план</strong></div><div class="header-actions">'+b('export','Экспорт')+'<label class="upload-button">Импорт<input type="file" id="planner-import" accept=".json,application/json"></label><a href="./index.html#content">Прежняя версия</a></div></header><main class="planner-main"><div class="context-bar">'+select('orgId','Организация',u.orgId,optionRows(orgs,'Выберите организацию'),'data-select="orgId"')+select('projId',u.archive?'Проект · архив':'Проект',u.projId,optionRows(projects,'Выберите проект'),'data-select="projId"')+'<details class="management"><summary>Управление</summary><div class="management-menu">'+b('org-create','Создать организацию')+(org?b('org-edit','Изменить организацию')+b('project-create','Создать проект')+b('archive-list',u.archive?'Активные проекты':'Архив проектов'):'')+(project?b('project-edit','Изменить проект')+b('project-archive',project.archived?'Восстановить проект':'В архив')+b('works','Работы проекта'):'')+'</div></details></div>';
 if(!org)return h+'<section class="empty-panel"><h1>Соберите план проекта</h1><p>Выберите организацию или создайте её. Для «Бодрого Боцмана» одна лодка — один проект. Здесь же можно вести проекты других клиентов.</p>'+b('org-create','Создать организацию','','primary')+'</section></main>';
 if(!project)return h+'<section class="empty-panel"><h1>Выберите проект</h1><p>Для лодки или катера создайте один проект и добавляйте в него работы по мере выполнения. Для клиента или модели используйте такой же проект.</p>'+b('project-create','Создать проект','','primary')+'</section></main>';
 h+='<div class="project-heading"><div><h1>'+e(project.name)+'</h1><span>'+quantity(topics.length,['тема','темы','тем'])+' · '+quantity(p.works.filter(x=>x.projId===project.id).length,['работа','работы','работ'])+'</span></div>'+b('topic-create','＋ Новая тема','','primary')+'</div><nav class="main-tabs" aria-label="Разделы плана">'+[['plan','План'],['week','Неделя'],['scripts','Сценарии'],['publications','Публикации']].map(([v,t])=>b('view',t,'data-view="'+v+'" aria-pressed="'+(u.view===v)+'"',u.view===v?'active':'')).join('')+'</nav><div class="working-grid '+(u.draft?'has-editor':'')+'"><section class="list-surface" id="plan-list">';
 if(u.view==='plan')h+=topics.length?'<div class="plan-table-wrap"><table class="plan-table"><thead><tr><th>Тема / работы</th><th>Сценарий</th><th>Съёмка</th><th>Публикации</th><th>Подготовка</th><th>Согласование</th></tr></thead><tbody>'+topics.map(t=>{const works=p.works.filter(x=>t.workIds.includes(x.id)),dates=t.variants.map(v=>v.date).filter(Boolean).sort(),urgent=t.scenes.filter(x=>x.beforeWork&&!x.filmed);return '<tr data-action="topic-open" data-id="'+e(t.id)+'" '+(u.draft?.id===t.id?'class="selected"':'')+'><td>'+open(t,e(t.title))+'<small>'+e(works.map(x=>x.name).join(' · ')||'Работы не выбраны')+'</small></td><td>'+(t.script?.trim()?'Есть текст':'Нет сценария')+'</td><td>'+t.scenes.filter(x=>x.filmed).length+' / '+t.scenes.length+' снято'+(urgent.length?'<small class="urgent">До работ: '+urgent.length+'</small>':'')+'</td><td>'+dateLabel(dates[0])+'<small>'+e(t.variants.map(v=>v.platform+' · '+v.format).join(', ')||'Площадки не выбраны')+'</small></td><td>'+t.preparation.filter(x=>x.done).length+' / '+t.preparation.length+'</td><td>'+approvalTag(t)+'</td></tr>';}).join('')+'</tbody></table></div>':emptyTopics();
 if(u.view==='scripts')h+=topics.length?'<div class="topic-cards">'+topics.map(t=>'<article class="topic-card">'+open(t,e(t.title))+'<div class="card-meta">'+approvalTag(t)+'<span>'+t.scenes.length+' сцен</span></div><pre>'+e(t.script||'Сценарий ещё не составлен')+'</pre>'+b('topic-open','Открыть сценарий','data-id="'+e(t.id)+'" data-tab="script"')+'</article>').join('')+'</div>':emptyTopics();
 if(u.view==='publications'){const rows=topics.flatMap(t=>t.variants.map(v=>({t,v}))).sort((a,b)=>(a.v.date||'').localeCompare(b.v.date||''));h+=rows.length?'<div class="publication-cards">'+rows.map(({t,v})=>'<article class="topic-card"><div class="card-meta"><strong>'+e(v.platform)+' · '+e(v.format)+'</strong><span>'+dateLabel(v.date)+'</span></div>'+open(t,e(t.title))+'<div class="card-meta">'+badge(v.ready||'Черновик',v.ready==='Опубликовано'?'#28745b':'#7054d8')+approvalTag(t)+'</div><pre>'+e(v.text||'Вариант текста пока пуст')+'</pre>'+b('topic-open','Открыть публикацию','data-id="'+e(t.id)+'" data-tab="variants"')+'</article>').join('')+'</div>':'<div class="empty-state"><h2>Нет вариантов публикации</h2><p>Откройте тему и выберите площадку, затем формат. Общая тема останется одна.</p></div>';}
 if(u.view==='week'){
 const events=weekEvents(s,project.id,u.week);h+='<div class="week-toolbar">'+b('week-prev','‹','aria-label="Предыдущие семь дней"')+'<strong>'+dateLabel(u.week)+' — '+dateLabel(addDays(u.week,6))+'</strong>'+b('week-next','›','aria-label="Следующие семь дней"')+b('week-today','Сегодня')+'</div><p class="small-note">Даты по Москве · съёмки, крайние сроки и публикации выбранного проекта</p><div class="week-board">'+Array.from({length:7},(_,i)=>{const day=addDays(u.week,i);return '<section class="week-column"><h2>'+new Date(day+'T12:00Z').toLocaleDateString('ru-RU',{weekday:'short',day:'numeric',month:'short',timeZone:'Europe/Moscow'})+'</h2>'+events.filter(x=>x.date===day).map(x=>b(x.topic?'topic-open':'legacy-shoot','<span class="event-kind">'+({shoot:'Съёмка',deadline:'Крайний срок',post:'Публикация','legacy-shoot':'Съёмка'}[x.kind])+'</span><strong>'+e(x.title)+'</strong><small>'+e(x.note)+(x.before?' · До начала работы':'')+'</small>','data-id="'+e(x.topic||x.shootId)+'" data-tab="'+(x.kind==='post'?'variants':'scenes')+'"','week-event '+x.kind)).join('')+(events.some(x=>x.date===day)?'':'<p class="no-events">Нет событий</p>')+'</section>';}).join('')+'</div>';}
 return h+'</section><aside class="editor-slot" id="topic-editor">'+(u.draft?editor(s,u):'')+'</aside></div></main>';
}
function emptyTopics(){return '<div class="empty-state"><h2>План пока пуст</h2><p>Начните с темы: что нужно показать, какие работы и кадры связаны с ней. Сценарий и варианты для площадок добавите в той же карточке.</p>'+b('topic-create','＋ Новая тема','','primary')+'</div>';}
export function editor(s,u){
 if(u.wizard)return questionView(s,u);
 if(!u.sectionOnly&&!u.wizard){
 const tabs=[['topic','Основное'],['script','Сценарий'],['scenes','Съёмки и кадры'],['variants','Публикации']],key=tabs.some(([v])=>v===u.editorTab)?u.editorTab:'topic';
 const html=editor(s,{...u,sectionOnly:true,editorTab:key}),body=html.split('<div class="editor-body">')[1].split('</div><footer>')[0];
 return '<form id="topic-form" class="topic-editor spacious-editor tabbed-editor"><header><div><span class="small-note">'+e(s.projects.find(x=>x.id===u.draft.projId)?.name||'Проект')+' / Тема</span><h2>'+e(u.draft.title||'Новая тема')+'</h2></div>'+(plannerState(s).topics.some(t=>t.id===u.draft.id)?b('shoot-open','На съёмке','data-topic="'+e(u.draft.id)+'"'):'')+b('editor-close','← К плану')+'</header><nav class="material-tabs" role="tablist" aria-label="Разделы темы">'+tabs.map(([v,title])=>b('editor-tab',title,'id="material-tab-'+v+'" role="tab" aria-selected="'+(key===v)+'" aria-controls="section-'+v+'" tabindex="'+(key===v?'0':'-1')+'" data-tab="'+v+'"',key===v?'active':'')).join('')+'</nav><div class="editor-body"><section id="section-'+key+'" role="tabpanel" aria-labelledby="material-tab-'+key+'" class="tabbed-panel">'+body+'</section></div><footer><span class="save-note" role="status">'+(u.dirty?'Есть несохранённые изменения':'Сохраняется вся тема, включая другие разделы')+'</span>'+b('editor-close','Отмена')+'<button type="submit" class="primary">Сохранить тему</button></footer></form>';
 }

 const t=u.draft,p=plannerState(s),works=p.works.filter(x=>x.projId===t.projId),input=(name,label,type='text',value=t[name]||'')=>field(name,label,value,type),sel=(name,label,value,rows)=>select(name,label,value,rows);
 let h='<form id="topic-form" class="topic-editor"><header><div><span class="small-note">'+e(s.projects.find(x=>x.id===t.projId)?.name||'Проект')+' / Тема</span><h2>'+e(t.title||'Новая тема')+'</h2></div>'+b('editor-close','×','aria-label="Закрыть редактор"','close-button')+'</header><nav class="editor-tabs" aria-label="Разделы темы">'+[['topic','Тема'],['script','Сценарий'],['scenes','Сцены'],['variants','Площадки']].map(([v,label])=>b('editor-tab',label,'data-tab="'+v+'"',u.editorTab===v?'active':'')).join('')+'</nav><div class="editor-body">';
 
 if(u.editorTab==='topic')h+='<div class="basic-fields">'+input('title','Тема')+input('day','Дата для новых публикаций','date')+'</div><p class="small-note">Эта дата подставляется только при добавлении нового варианта. Даты уже существующих публикаций меняются отдельно на вкладке «Публикации».</p><details class="material-extra"><summary>Дополнительно · папка и категория</summary><div class="field-pair">'+sel('folderPick','Папка (необязательно)',scopeFolders(s,u).find(f=>(t.folderIds||[]).includes(f.id))?.id||'',optionRows(scopeFolders(s,u),'Без папки'))+sel('rubric','Категория контента (необязательно)',t.rubric,optionRows(s.rubrics,'Без категории'))+'</div><p class="small-note">Категория объединяет темы по направлению контента. Она не влияет на даты или площадки.</p></details><fieldset><legend>Работы проекта</legend>'+(works.length?works.map(w=>'<label class="checkbox-line"><input type="checkbox" data-work-id="'+e(w.id)+'" '+(t.workIds.includes(w.id)?'checked':'')+'>'+e(w.name)+'</label>').join(''):'<p class="small-note">Работы пока не добавлены.</p>')+b('works','Работы проекта')+'</fieldset><h3>Подготовка</h3>'+t.preparation.map(x=>'<div class="checklist-row"><input type="checkbox" data-prep-done="'+e(x.id)+'" '+(x.done?'checked':'')+' aria-label="Выполнено"><input data-prep-text="'+e(x.id)+'" value="'+e(x.text)+'" aria-label="Действие подготовки"><label class="prep-deadline-field">Дедлайн подготовки<input type="date" data-prep-deadline="'+e(x.id)+'" value="'+e(x.deadline||'')+'"></label>'+b('prep-remove','×','data-id="'+e(x.id)+'" aria-label="Удалить действие"')+'</div>').join('')+b('prep-add','＋ Действие')+'<section class="approval-section"><h3>Согласование</h3>'+sel('approval','Отметка согласования',t.approval,approval.map(x=>[x,x]))+input('approvalNote','Комментарий после разговора','textarea')+'<p class="small-note">Локальная отметка. Доступ директора к этой карточке ещё не подключён.</p></section>';
 if(u.editorTab==='script')h+='<div class="script-heading"><h3>Общий сценарий темы</h3>'+b('wizard-open','Создать с AI · вопросы')+'</div>'+(t.script?.trim()||u.manualScript?input('script','Сценарий','textarea'):'<div class="qa-empty"><p>Начните с вопросов: тема, факты и кадры. После ответов AI подготовит сценарий и раскадровку, когда OpenAI API будет настроен.</p>'+b('wizard-open','Ответить на вопросы','','primary')+b('script-manual','Написать вручную')+'</div>')+'<p class="small-note">Общий сценарий связан со сценами. Варианты текстов для соцсетей находятся в «Площадках».</p>'+(t.answers&&Object.keys(t.answers).length?'<details><summary>Сохранённые ответы мастера</summary><pre class="answers-preview">'+e(Object.entries(t.answers).filter(([,v])=>v).map(([k,v])=>(answerLabels[k]||k)+': '+v).join('\n'))+'</pre></details>':'');
 if(u.editorTab==='script')h+='<section class="draft-script-scenes">'+storyboardEditor(s,t)+'</section>';
 if(u.editorTab==='scenes')h+='<p class="small-note">Здесь те же сцены, что в сценарии. Уточните даты, статусы, работы и референсы. Все правки сохраняются вместе с темой.</p>'+storyboardEditor(s,t);
 if(u.editorTab==='variants')h+='<div class="script-heading"><h3>Варианты публикации</h3>'+b('variant-add','＋ Площадка')+'</div>'+t.variants.map(v=>variantForm(v)).join('')+(!t.variants.length?'<p class="small-note">Сначала выберите площадку, затем допустимый формат. Каждый вариант имеет свой текст, дату и готовность.</p>':'');
 h+='</div><footer><span class="save-note">'+(u.dirty?'Есть несохранённые изменения':'Изменения сохраняются кнопкой')+'</span>'+b('editor-close','Отмена')+'<button type="submit" class="primary">Сохранить</button></footer></form>';
 return h;
}
export const answerLabels={problem:'Что делаем и проблема до ремонта',work:'Этап / работа',audience:'Кому видео',goal:'Цель',platform:'Площадка',format:'Формат',available:'Что доступно снять',mustCapture:'Что нельзя пропустить',facts:'Подтверждённые факты / результат',speaker:'Кто в кадре или говорит',speakerMode:'Режим речи',durationSeconds:'Длительность, секунд',length:'Желаемая длина',tone:'Тон',shootDate:'Дата съёмки',deadline:'Крайний срок'};
function variantForm(v){const choices=platforms[v.platform]||[],video=['Reels','Shorts','Видео','Клип','Выпуск'].includes(v.format),photo=['Фото','Публикация','Альбом','Пост'].includes(v.format);return '<section class="variant-card" data-variant="'+e(v.id)+'">'+select('variant-platform-'+v.id,'1. Площадка',v.platform||'',[['','Выберите площадку'],...Object.keys(platforms).map(x=>[x,x]),...(v.platform&&!platforms[v.platform]?[[v.platform,v.platform]]:[])])+(v.platform?select('variant-format-'+v.id,'2. Формат',v.format||'',[['','Выберите формат'],...choices.map(x=>[x,x]),...(v.format&&!choices.includes(v.format)?[[v.format,v.format+' (прежний формат)']]:[])]):'')+(v.platform&&v.format?'<div class="field-pair">'+field('variant-date-'+v.id,'Дата публикации',v.date||'','date')+select('variant-ready-'+v.id,'Готовность',v.ready||'Черновик',readiness.map(x=>[x,x]))+'</div>'+field('variant-text-'+v.id,video?'Описание / реплики для видео':'Текст этого варианта',v.text||'','textarea')+(video?field('variant-duration-'+v.id,'Длительность',v.duration||'')+field('variant-videoNotes-'+v.id,'Монтаж / файл видео',v.videoNotes||'','textarea'):'')+(photo?field('variant-photoNotes-'+v.id,'Какие фотографии выбрать',v.photoNotes||'','textarea'):'')+field('variant-link-'+v.id,'Ссылка на тему',v.link||'','url'):'')+b('variant-remove','Удалить вариант','data-id="'+e(v.id)+'"','danger')+'</section>';}
function sceneWarning(scene,works){const risky=works.filter(w=>(scene.workIds||[]).includes(w.id)&&w.startDate&&scene.beforeWork&&!scene.filmed&&(!scene.deadline||scene.deadline>=w.startDate||scene.date>=w.startDate));return risky.length?'<p class="warning">Сначала снимите исходное состояние: '+e(risky.map(x=>x.name).join(', '))+'. Проверьте крайний срок до начала работ.</p>':'';}
function storyboard(s,scene){const file=s.files.find(x=>x.id===scene.storyboardFileId);return file&&/^data:image\/(png|jpeg|webp|gif|avif);base64,/.test(file.data||'')?'<img class="storyboard-image" src="'+e(file.data)+'" alt="Раскадровка: '+e(file.name)+'">':'';}

