import {shootRecords,selectedShot} from './shooting-mode.js?v=20261008-single-plan8';
import {initializeQuestions,validateQuestions,requestBrief,aiConnection,generateScenario,resultScenes,acceptScenario} from './qa-scenario.js?v=20261008-single-plan8';
import {changeTableDate,linkedShoots,ungroupedShoots} from './table-records.js?v=20261008-single-plan8';
import {nextProjectColor,validColor} from './project-colors.js?v=20261008-single-plan8';
import {planScenes,scenarioText,planPreview,appendPlan,speakers} from './scenario-plan.js?v=20261008-single-plan8';
import {seconds,retimeScenes} from './scene-timing.js?v=20261008-single-plan8';
import {monthShift} from './content-calendar.js?v=20261008-single-plan8';
import {newShot,shotFields,shotStatus,shotStatuses} from './storyboard.js?v=20261008-single-plan8';
import {quickCreate} from './quick-create.js?v=20261008-single-plan8';
import {openStore,persist} from './storage.js?v=20261008-single-plan8';
import {uid,normalize,removeEntity} from './model.js?v=20261008-single-plan8';
import {escape as e,field,openDialog,toast,button as b,safeUrl} from './ui.js?v=20261008-single-plan8';
import {editor} from './planner-view.js?v=20261008-single-plan8';
import {view} from './reference-view.js?v=20261008-single-plan8';
import {scope,owner,scopeFolders,moveToFolder} from './folder-model.js?v=20261008-single-plan8';
import {platforms,plannerState,newTopic,importLegacy,saveTopic,moscowDate,addDays,validDate} from './planner-model.js?v=20261008-single-plan8';
let state,busy=false,aiAbort=null,aiRun=0;
const u={navScope:'projects',folderId:'',orgId:'',projId:'',archive:false,view:'table',calendarMode:'week',calendarDate:moscowDate(),channel:'',scriptEdits:{},tableDate:null,boardTopic:'',boardFilter:'all',calendarMonth:moscowDate().slice(0,7)+'-01',week:moscowDate(),draft:null,dirty:false,editorTab:'topic',wizard:false,wizardStep:0};
const $=selector=>document.querySelector(selector);
function fitEditor(){if($('.spacious-editor'))return;const node=$('.topic-editor');if(node&&innerWidth>780)node.style.setProperty('--editor-height',Math.max(360,innerHeight-node.getBoundingClientRect().top-24)+'px');}
function render(){document.documentElement.style.setProperty('--font',(state.settings?.fontSize||15)+'px');document.documentElement.dataset.theme=state.settings?.theme||'light';document.documentElement.style.setProperty('--sidebar',(state.settings?.navWidth||236)+'px');document.documentElement.style.setProperty('--accent',state.settings?.accent&&state.settings.accent!=='#28745b'?state.settings.accent:'#7561df');const opened=[...document.querySelectorAll('[data-plan-detail][open]')].map(x=>x.dataset.planDetail),query=$('#reference-search')?.value||'';const scroll=$('#plan-list')?.scrollTop||0,left=$('.plan-table-wrap')?.scrollLeft||0,top=scrollY;$('#planner').innerHTML=view(state,u);document.querySelectorAll('[data-plan-detail]').forEach(x=>{x.open=opened.includes(x.dataset.planDetail)});if(u.tableDate){const field=$('[data-table-date-input]');if(field){field.closest('details')?.setAttribute('open','');setTimeout(()=>field.focus(),0)}}if($('#reference-search')&&query){$('#reference-search').value=query;$('#reference-search').dispatchEvent(new Event('input',{bubbles:true}))}if($('#plan-list'))$('#plan-list').scrollTop=scroll;if($('.plan-table-wrap'))$('.plan-table-wrap').scrollLeft=left;scrollTo(0,top);fitEditor();remember();}
function renderEditor(){const openShots=[...document.querySelectorAll('.shot-detail[open]')].map(x=>x.closest('.shot-card').querySelector('[data-action=scene-move]')?.dataset.id);const top=scrollY;const scroll=$('.editor-body')?.scrollTop||0;$('#topic-editor').innerHTML=u.draft?editor(state,u):'';document.querySelectorAll('.shot-card').forEach(card=>{if(openShots.includes(card.querySelector('[data-action=scene-move]')?.dataset.id))card.querySelector('.shot-detail').open=true;});if($('.editor-body'))$('.editor-body').scrollTop=scroll;scrollTo(0,top);fitEditor();}
window.addEventListener('resize',fitEditor);
function remember(){try{localStorage.setItem('studio-planner-context',JSON.stringify({orgId:u.orgId,projId:u.projId,archive:u.archive,navScope:u.navScope,folderId:u.folderId,view:u.view,scenarioView:u.scenarioView,calendarMode:u.calendarMode,calendarDate:u.calendarDate}))}catch{}}
function selectInitial(){u.navScope='projects';if(!['week','month','half','day'].includes(u.calendarMode))u.calendarMode='week';if(!validDate(u.calendarDate)||!u.calendarDate)u.calendarDate=moscowDate();const org=state.orgs.find(x=>x.id===u.orgId)||state.orgs.find(x=>x.name.trim().toLowerCase()==='бодрый боцман')||state.orgs[0];u.orgId=org?.id||'';const project=state.projects.find(x=>x.id===u.projId&&x.orgId===u.orgId&&Boolean(x.archived)===u.archive)||state.projects.find(x=>x.orgId===u.orgId&&Boolean(x.archived)===u.archive);u.projId=project?.id||'';if(!['projects','organizations'].includes(u.navScope))u.navScope='projects';if(u.folderId&&!scopeFolders(state,u).some(f=>f.id===u.folderId))u.folderId='';}
async function commit(next,message='Сохранено'){if(busy)throw Error('Дождитесь сохранения');busy=true;document.querySelectorAll('[data-action=shoot-status],[data-action=shoot-note-save]').forEach(x=>x.disabled=true);try{await persist(next);state=next;render();toast(message)}finally{busy=false}}
function confirm(title,body,callback,label='Подтвердить'){openDialog(title,'<p>'+e(body)+'</p>',callback);$('#modal button[type=submit]').textContent=label;}
function guard(action){if(!u.dirty&&!u.tableDate&&!u.shootNoteDirty)return action();confirm('Есть несохранённые изменения','Продолжить без сохранения? Изменения материала, сценариев, выбранной даты или заметки к кадру будут отменены.',()=>{u.draft=null;u.scriptEdits={};u.tableDate=null;u.dirty=false;u.shootNoteDirty=false;u.shootNoteDraft=null;u.wizard=false;render();action()},'Закрыть без сохранения');}
function openTopic(id,tab='topic'){guard(()=>{const topic=plannerState(state).topics.find(x=>x.id===id);if(!topic)throw Error('Тема не найдена');u.projId=topic.projId;u.draft=structuredClone(topic);u.dirty=false;u.editorTab=tab;u.wizard=false;u.manualScript=false;render();scrollTo(0,0);if(tab!=='topic')$('#section-'+tab)?.scrollIntoView();const heading=$('#topic-editor h2');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true})}});}
function closeEditor(){guard(()=>{u.draft=null;u.dirty=false;u.wizard=false;render()})}
function entity(type,existing=null){
 const isOrg=type==='orgs',title=isOrg?'Организация':'Проект',x=existing||{};
 const html=field('name',isOrg?'Название организации':'Название проекта / лодки / клиента',x.name||'','text',null,true)+(isOrg?'':field('color','Цвет проекта',x.color||nextProjectColor(state.projects),'color')+field('description','Описание проекта',x.description||'','textarea')+'<div class="field-pair">'+field('startDate','Начало',x.startDate||'','date')+field('endDate','Ориентир завершения',x.endDate||'','date')+'</div>');
 openDialog((existing?'Изменить: ':'Создать: ')+title,html,async data=>{data.name=data.name.trim();if(!isOrg&&!validColor(data.color))throw Error('Выберите цвет проекта');if(!data.name)throw Error('Введите название');for(const key of ['startDate','endDate'])if(data[key]&&!validDate(data[key]))throw Error('Проверьте дату');if(data.startDate&&data.endDate&&data.startDate>data.endDate)throw Error('Завершение раньше начала');
 if(isOrg&&!existing){const duplicate=state.orgs.find(x=>x.name.trim().toLowerCase()===data.name.toLowerCase());if(duplicate){u.draft=null;u.dirty=false;u.wizard=false;u.orgId=duplicate.id;u.projId='';u.archive=false;selectInitial();render();toast('Выбрана существующая организация');return;}}
 const record={...x,...data,id:x.id||uid(),...(isOrg?{}:{orgId:x.orgId||u.orgId,archived:Boolean(x.archived)})},next=structuredClone(state);next[type]=next[type].filter(v=>v.id!==record.id);next[type].push(record);u.draft=null;u.dirty=false;u.wizard=false;if(isOrg){u.orgId=record.id;u.projId='';u.folderId='';u.channel='';u.archive=false;}else{if(u.navScope==='projects'&&u.projId!==record.id)u.folderId='';u.projId=record.id;u.channel='';u.archive=record.archived;}await commit(next);});
}
function worksDialog(){const works=plannerState(state).works.filter(x=>x.projId===u.projId);openDialog('Работы по проекту с сайта bodr-bo','<p class="small-note">Работы вводятся вручную. Интеграция с программой Боцмана пока не подключена.</p>'+works.map(w=>'<div class="work-row"><div><strong>'+e(w.name)+'</strong><small>'+e(w.startDate||'Дата начала не назначена')+(w.irreversible?' · Необратимая работа':'')+'</small></div>'+b('work-edit','Изменить','data-id="'+e(w.id)+'"')+'</div>').join('')+b('work-create','＋ Работа','','primary'),null,true);}
function editWork(id){const x=plannerState(state).works.find(x=>x.id===id)||{},html=field('name','Название работы',x.name||'','text',null,true)+field('description','Что делаем',x.description||'','textarea')+field('startDate','Ориентир начала',x.startDate||'','date')+'<label class="checkbox-line"><input type="checkbox" name="irreversible" '+(x.irreversible?'checked':'')+'>После начала нельзя снять исходное состояние</label>';openDialog(id?'Изменить работу':'Добавить работу',html,async data=>{if(!data.name.trim())throw Error('Введите название');if(!validDate(data.startDate))throw Error('Проверьте дату');const next=structuredClone(state);next.planner=plannerState(next);const record={...x,...data,name:data.name.trim(),irreversible:!!data.irreversible,id:x.id||uid(),projId:x.projId||u.projId};next.planner.works=next.planner.works.filter(v=>v.id!==record.id);next.planner.works.push(record);await commit(next);});}
function projectLink(id=''){guard(()=>{const old=state.links.find(x=>x.id===id&&x.projId===u.projId);openDialog(old?'Изменить ссылку':'Добавить ссылку',field('name','Название',old?.name||'','text',null,true)+field('url','Адрес',old?.url||'','url',null,true),async data=>{if(!data.name.trim())throw Error('Введите название');if(!safeUrl(data.url))throw Error('Укажите ссылку http:// или https://');const next=structuredClone(state),record={...old,id:old?.id||uid(),projId:u.projId,name:data.name.trim(),url:safeUrl(data.url)};next.links=old?next.links.map(x=>x.id===old.id?record:x):[...next.links,record];await commit(next);});});}
function fileDownload(id){const file=state.files.find(x=>x.id===id&&x.projId===u.projId);if(!file||!/^data:[^,]*;base64,/.test(file.data||''))throw Error('Файл повреждён');const raw=atob(file.data.split(',')[1]),blob=new Blob([Uint8Array.from(raw,c=>c.charCodeAt(0))],{type:file.type||'application/octet-stream'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function fileView(id){const file=state.files.find(x=>x.id===id&&x.projId===u.projId);if(!file)return;let preview='<p>Для этого формата доступно скачивание.</p>';if(/^data:image\/(png|jpeg|webp|gif|avif);base64,/.test(file.data||''))preview='<img class="project-file-preview" src="'+e(file.data)+'" alt="'+e(file.name)+'">';else if(/^data:video\/[a-z0-9.+-]+;base64,/i.test(file.data||''))preview='<video controls class="project-file-preview" src="'+e(file.data)+'"></video>';else if(/^data:audio\/[a-z0-9.+-]+;base64,/i.test(file.data||''))preview='<audio controls src="'+e(file.data)+'"></audio>';else if(/^data:application\/pdf;base64,/.test(file.data||''))preview='<iframe sandbox class="project-file-preview" src="'+e(file.data)+'" title="'+e(file.name)+'"></iframe>';openDialog(file.name,preview+b('project-file-download','Скачать','data-id="'+e(id)+'"'),null,true);}
function moveShot(topic,id,direction){const index=topic.scenes.findIndex(x=>x.id===id),target=index+Number(direction);if(index>=0&&target>=0&&target<topic.scenes.length)[topic.scenes[index],topic.scenes[target]]=[topic.scenes[target],topic.scenes[index]];}
function boardGuard(action){if(u.draft&&u.dirty)return guard(action);return action();}
function editBoard(topicId='',id=''){boardGuard(()=>{
 const topics=plannerState(state).topics.filter(t=>t.projId===u.projId),topic=topics.find(t=>t.id===topicId)||topics.find(t=>t.id===u.boardTopic)||topics[0];if(!topic){toast('Сначала добавьте тему через «Создать → Добавить тему»');return;}
 const current=topic.scenes.find(x=>x.id===id),shot=current?structuredClone(current):newShot(uid());
 const body=field('shotTopic','Сценарий / тема',topic.id,'text',topics.map(t=>[t.id,t.title]))+shotFields(state,topic,shot);
 openDialog(current?'Изменить кадр':'Добавить кадр',body,async data=>{
 const target=plannerState(state).topics.find(t=>t.id===data.shotTopic);if(!target||target.projId!==u.projId)throw Error('Сценарий не найден');const copy=structuredClone(target);
 for(const key of ['title','shots','timeStart','timeEnd','speech','voiceOver','broll','overlay','plan','status','audio','date','deadline','stage','beforeNote','storyboardFileId','shootId'])shot[key]=data['scene-'+key+'-'+shot.id]||'';
 shot.filmed=shot.status==='Снято';shot.beforeWork=Boolean($('#modal [data-scene-flag=beforeWork]')?.checked);shot.workIds=[...document.querySelectorAll('#modal [data-scene-work]:checked')].map(x=>x.dataset.sceneWork);
 let next=state;
 if(current&&target.id!==topic.id){const source=structuredClone(plannerState(state).topics.find(t=>t.id===topic.id));source.scenes=source.scenes.filter(x=>x.id!==id);next=saveTopic(next,source);copy.scenes.push(shot);}else if(current)copy.scenes=copy.scenes.map(x=>x.id===id?shot:x);else copy.scenes.push(shot);
 await commit(saveTopic(next,copy),'Кадр сохранён');
 },true);$('#modal').classList.add('shot-dialog');
 });}
function planDialog(topic,draft=false,answers=null){const a=answers||topic.answers||{},brief={...topic.aiBrief,topic:topic.title,platform:a.platform||topic.aiBrief?.platform||topic.variants[0]?.platform||'',format:a.format||topic.aiBrief?.format||topic.variants[0]?.format||'',facts:a.facts||topic.aiBrief?.facts||'',mustCapture:a.mustCapture||topic.aiBrief?.mustCapture||'',available:a.available||'',problem:a.problem||'',work:a.work||'',speakerMode:a.speakerMode||topic.aiBrief?.speakerMode||'host',durationSeconds:a.durationSeconds||topic.aiBrief?.durationSeconds||60,workIds:topic.workIds||[],shootDate:a.shootDate||'',deadline:a.deadline||''},works=plannerState(state).works.filter(w=>w.projId===topic.projId);let generated;
 const body=field('durationSeconds','Длительность нового плана, секунд',brief.durationSeconds,'number',null,true)+field('speakerMode','Кто говорит',brief.speakerMode,'text',speakers)+field('facts','Подтверждённые факты для черновых реплик',brief.facts,'textarea')+(topic.scenes.length?field('planMode','Как сохранить',answers?'text':'append','text',[...(answers?[['text','Только добавить текст черновика']]:[]),['append','Добавить новые сцены после существующих']])+'<p class="small-note">Существующие кадры и их реплики сохранятся. Новые сцены добавятся в конец. Проверьте план перед добавлением.</p>':'')+'<div class="scene-template-preview"></div>';
 openDialog('Составить раскадровку · предпросмотр',body,async data=>{const input={...brief,...data},scenes=planScenes(input,uid,works),current=draft?u.draft:plannerState(state).topics.find(t=>t.id===topic.id&&t.projId===u.projId);if(!current)throw Error('Сценарий не найден');const copy=structuredClone(current);if(data.planMode!=='text')copy.scenes=copy.scenes.length?appendPlan(copy.scenes,scenes):scenes;if(answers)copy.script+=(copy.script?'\n\n':'')+scenarioText(input,scenes);copy.aiBrief={...(copy.aiBrief||{}),...input,durationSeconds:Number(input.durationSeconds)};if(draft){u.draft=copy;u.dirty=true;u.wizard=false;render();toast('Черновик подготовлен. Сохраните сценарий.');}else await commit(saveTopic(state,copy),'Раскадровка добавлена');},true);
 const form=$('#modal form'),preview=()=>{try{const input={...brief,...Object.fromEntries(new FormData(form))};generated=planScenes(input,()=>'',works);form.querySelector('.scene-template-preview').innerHTML=planPreview(topic.scenes.length?appendPlan(topic.scenes,generated).slice(topic.scenes.length):generated);}catch(err){form.querySelector('.scene-template-preview').innerHTML='<p>'+e(err.message)+'</p>';}};form.oninput=preview;form.onchange=preview;preview();
}
function durationDialog(topicId,id){const draft=u.draft?.id===topicId,topic=draft?u.draft:plannerState(state).topics.find(t=>t.id===topicId&&t.projId===u.projId),x=topic?.scenes.find(x=>x.id===id);if(!x)return;const a=seconds(x.timeStart),z=seconds(x.timeEnd);openDialog('Изменить длительность сцены',field('seconds','Длительность, секунд',a!==null&&z!==null&&z>a?z-a:5,'number',null,true)+'<p>Следующие сцены сдвинутся по порядку. Их длительности, реплики и даты съёмки сохранятся. Для кадров без тайминга будет задано 5 секунд.</p>',async data=>{const current=draft?u.draft:plannerState(state).topics.find(t=>t.id===topicId&&t.projId===u.projId),copy=structuredClone(current);copy.scenes=retimeScenes(copy.scenes,id,data.seconds);if(draft){u.draft=copy;u.dirty=true;renderEditor();}else await commit(saveTopic(state,copy),'Тайминг пересчитан');});}
function dayActions(day){if(!day||!validDate(day))return;guard(()=>openDialog('Действия на '+new Date(day+'T12:00Z').toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Moscow'}),'<p class="small-note">Выбранная дата сразу подставится в форму.</p><div class="day-create-options">'+b('quick-create','Назначить съёмку','data-kind="shoot" data-day="'+day+'"')+b('calendar-task-add','Добавить задачу','data-day="'+day+'"')+b('quick-create','Запланировать публикацию','data-kind="post" data-day="'+day+'"')+b('calendar-day','Открыть этот день','data-day="'+day+'"')+'</div>',null));}
function calendarTask(day,id=''){const old=state.tasks.find(t=>t.id===id&&t.projId===u.projId);if(id&&!old)return;const projId=old?.projId||u.projId;openDialog(old?'Изменить задачу':'Задача на выбранную дату',field('text','Что нужно сделать',old?.text||'','text',null,true)+field('date','Дата / срок',old?.date||day,'date',null,true)+field('priority','Приоритет',old?.priority||'medium','text',[['low','Низкий'],['medium','Средний'],['high','Высокий']])+(old?'<label class="checkbox-line"><input type="checkbox" name="done" '+(old.done?'checked':'')+'>Выполнена</label>':'')+'<p class="small-note">Задача появится в календаре этого проекта и в общем разделе «Задачи».</p>',async data=>{if(!data.text.trim())throw Error('Введите задачу');if(!data.date||!validDate(data.date))throw Error('Проверьте дату');if(!state.projects.some(p=>p.id===projId))throw Error('Проект не найден');const next=structuredClone(state),task={...old,id:old?.id||uid(),projId,text:data.text.trim(),date:data.date,priority:data.priority,done:Boolean(data.done)};next.tasks=old?next.tasks.map(t=>t.id===id?task:t):[...next.tasks,task];await commit(next,'Задача сохранена');});}
function startScript(){guard(()=>{if(!u.projId){toast('Сначала выберите проект');return;}u.draft=newTopic(u.projId);u.draft.folderIds=u.folderId?[u.folderId]:[];u.editorTab='script';u.dirty=false;render();startQuestions();});}
function startQuestions(){initializeQuestions(u.draft);u.wizard=true;u.wizardStep=0;u.aiResult=null;u.aiError='';u.aiRequestId=null;renderEditor();aiConnection().then(x=>{u.aiConnection=x;if(u.wizard)renderEditor()});}
async function runGeneration(){if(u.aiLoading)return;validateQuestions(u.draft);const run=++aiRun;aiAbort=new AbortController();u.aiLoading=true;u.aiError='';renderEditor();const connection=await aiConnection(aiAbort.signal);if(run!==aiRun)return;u.aiConnection=connection;if(!connection.ready){u.aiLoading=false;u.aiError=connection.message;renderEditor();return;}const brief=requestBrief(state,u.draft);u.aiRequestId=u.aiRequestId||uid();u.aiLoading=true;u.aiError='';renderEditor();const timeout=setTimeout(()=>aiAbort?.abort(),105000);try{const result=await generateScenario(brief,connection,u.aiRequestId,aiAbort.signal);if(run!==aiRun)return;u.aiRequestId=null;resultScenes(result,u.draft);u.aiResult=result;u.aiRequestId=null;}catch(err){if(run!==aiRun)return;u.aiError=err.name==='AbortError'?'Ожидание прервано. Ответ не применён; запрос на сервере мог продолжиться.':err.message;if(err.status&&err.status!==409)u.aiRequestId=null;}finally{clearTimeout(timeout);if(run===aiRun){u.aiLoading=false;renderEditor();}}}
function stopGeneration(){aiRun++;aiAbort?.abort();u.aiLoading=false;}
function startQuick(kind,day=''){guard(()=>{if(!u.orgId){entity('orgs');return;}if(!u.projId){entity('projects');return;}document.querySelectorAll('.create-menu[open]').forEach(x=>x.open=false);quickCreate(state,u,kind,day,async(next,type)=>{u.channel='';await commit(next,type==='topic'?'Тема добавлена':type==='shoot'?'Съёмка добавлена':'Публикация добавлена');});});}
function download(){const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),data:state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='studio-content-plan-'+moscowDate()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('Экспорт включает старые записи и новый план');}
document.addEventListener('click',async event=>{const dateCell=event.target.closest('[data-calendar-date]');if(dateCell&&!event.target.closest('button,a,input,select,textarea,summary,details')){dayActions(dateCell.dataset.calendarDate);return;}if(event.target.closest('.table-detail')&&!event.target.closest('button[data-action]'))return;const btn=event.target.closest('[data-action]');if(!btn||!state)return;const {action,id,tab}=btn.dataset;try{if(busy){toast('Дождитесь сохранения');return;}
 if(action==='site-menu'||action==='site-menu-close'){const shell=$('.reference-shell'),open=action==='site-menu'&&!shell.classList.contains('mobile-nav-open');shell.classList.toggle('mobile-nav-open',open);$('[data-action=site-menu]')?.setAttribute('aria-expanded',String(open));}
 else if(action==='shoot-open')guard(()=>{u.draft=null;u.view='shooting';u.shootTopic=btn.dataset.topic||'';u.shootDate='';u.shootFilter='all';u.shootSelected='';u.shootDetail=false;u.shootNoteDraft=null;render();scrollTo(0,0)});
 else if(action==='shoot-back')guard(()=>{u.view='table';u.shootNoteDraft=null;render()});
 else if(action==='shoot-list')guard(()=>{u.shootDetail=false;u.shootNoteDraft=null;render()});
 else if(action==='shoot-select')guard(()=>{if(!shootRecords(state,u).some(r=>r.key===btn.dataset.key))u.shootDate='';u.shootSelected=btn.dataset.key;u.shootDetail=true;u.shootNoteDraft=null;render()});
 else if(action==='shoot-filter')guard(()=>{u.shootFilter=btn.dataset.filter;u.shootSelected='';u.shootDetail=false;u.shootNoteDraft=null;render()});
 else if(action==='shoot-scope')guard(()=>{u.shootTopic='';u.shootSelected='';u.shootDetail=false;u.shootNoteDraft=null;render()});
 else if(action==='shoot-next')guard(()=>{const list=shootRecords(state,u),current=selectedShot(state,u),remaining=list.filter(r=>shotStatus(r.scene)!=='Снято');const after=list.findIndex(r=>r.key===current?.key);const next=list.slice(after+1).find(r=>shotStatus(r.scene)!=='Снято')||remaining[0];if(next){u.shootSelected=next.key;u.shootDetail=true;u.shootNoteDraft=null;render()}else toast('Все кадры сняты');});
 else if(action==='shoot-status'||action==='shoot-note-save'){const current=selectedShot(state,u);if(!current)return;const topic=structuredClone(current.topic),scene=topic.scenes.find(x=>x.id===current.scene.id);if(u.shootNoteDirty){scene.shootNote=u.shootNoteDraft||'';}if(action==='shoot-status'){scene.status=btn.dataset.status;scene.filmed=scene.status==='Снято';}const next=saveTopic(state,topic);busy=true;document.querySelectorAll('[data-action=shoot-status],[data-action=shoot-note-save]').forEach(x=>x.disabled=true);try{await persist(next);state=next;}finally{busy=false;document.querySelectorAll('[data-action=shoot-status],[data-action=shoot-note-save]').forEach(x=>x.disabled=false);}u.shootNoteDirty=false;u.shootNoteDraft=null;render();toast(action==='shoot-note-save'?'Заметка сохранена':'Статус кадра сохранён');}
 else if(action==='calendar-mode'){u.calendarMode=btn.dataset.mode;render();}
 else if(action==='calendar-day'){$('#modal').close();u.calendarDate=btn.dataset.day;u.calendarMode='day';render();}
 else if(action==='calendar-prev'||action==='calendar-next'||action==='calendar-today'){const direction=action==='calendar-prev'?-1:1,date=u.calendarDate||moscowDate();u.calendarDate=action==='calendar-today'?moscowDate():u.calendarMode==='half'?monthShift(date,direction*6):u.calendarMode==='month'?monthShift(date,direction):addDays(date,direction*(u.calendarMode==='day'?1:7));render();}
 else if(action==='table-topic-toggle'){
  if(!plannerState(state).topics.some(t=>t.id===id&&t.projId===u.projId))return;
  const expanded=(u.expandedTopics||[]).includes(id),apply=()=>{u.expandedTopics=expanded?(u.expandedTopics||[]).filter(x=>x!==id):[...(u.expandedTopics||[]),id];render();[...document.querySelectorAll('[data-action=table-topic-toggle]')].find(x=>x.dataset.id===id)?.focus({preventScroll:true});};
  if(expanded&&u.tableDate?.topic===id)guard(apply);else apply();
 }
 else if(action==='table-date-edit'){
  if(u.tableDate){toast('Сначала сохраните или отмените редактирование даты');return;}
  const group=btn.dataset.group,key=btn.dataset.field,topic=plannerState(state).topics.find(t=>t.id===btn.dataset.topic&&t.projId===u.projId),record=group==='shoots'?state.shoots.find(x=>x.id===id):topic?.[group]?.find(x=>x.id===id);
  if(!record)return;
  if(group==='shoots'&&!(topic?linkedShoots(state,topic).some(x=>x.id===id):ungroupedShoots(state,u.projId).some(x=>x.id===id)))return;
  if(topic)u.expandedTopics=[...new Set([...(u.expandedTopics||[]),topic.id])];
  u.tableDate={topic:topic?.id||'',id,group,field:key,original:record[key]||'',value:record[key]||'',error:''};render();
 }
 else if(action==='table-date-cancel'){u.tableDate=null;render();}
 else if(action==='table-date-save'){
  const edit=u.tableDate;if(!edit)return;edit.value=$('[data-table-date-input]').value;
  try{const next=changeTableDate(state,u.projId,edit,edit.value);busy=true;btn.closest('.table-date-editor').querySelectorAll('button,input').forEach(x=>x.disabled=true);await persist(next);state=next;u.tableDate=null;render();toast('Дата выбранной записи сохранена');}catch(err){edit.error=err.message;render();}finally{busy=false;}
 }
 else if(action==='project-link-edit')projectLink(id);
 else if(action==='project-file-view')fileView(id);
 else if(action==='project-file-download'){fileDownload(id);const menu=btn.closest('details');if(menu)menu.open=false;}
 else if(action==='project-asset-delete'){const type=btn.dataset.type;if(!['links','files'].includes(type))return;const record=state[type].find(x=>x.id===id&&x.projId===u.projId);if(!record)return;confirm('Удалить '+(type==='files'?'файл':'ссылку'),'Удалить «'+record.name+'»?'+(type==='files'?' Кадры сохранятся, привязка этого референса будет снята.':''),async()=>{const next=structuredClone(state);next[type]=next[type].filter(x=>x.id!==id);if(type==='files')next.planner.topics.forEach(t=>t.scenes.forEach(x=>{if(x.storyboardFileId===id)x.storyboardFileId='';}));await commit(next);});}
 else if(action==='board-template')boardGuard(()=>{const topic=plannerState(state).topics.find(t=>t.id===btn.dataset.topic&&t.projId===u.projId);if(topic)planDialog(topic);});
 else if(action==='scene-duration')durationDialog(btn.dataset.topic,id);
 else if(action==='board-add'||action==='board-edit')editBoard(btn.dataset.topic||'',id||'');
 else if(action==='board-status'||action==='board-move'||action==='board-delete')await boardGuard(()=>{const topic=structuredClone(plannerState(state).topics.find(t=>t.id===btn.dataset.topic&&t.projId===u.projId));if(!topic)return;const shot=topic.scenes.find(x=>x.id===id);if(!shot)return;const save=()=>commit(saveTopic(state,topic),'Раскадровка обновлена');if(action==='board-delete')confirm('Удалить кадр','Удалить кадр из сценария и обзора проекта? Текст сценария сохранится.',()=>{topic.scenes=topic.scenes.filter(x=>x.id!==id);return save();});else{if(action==='board-move')moveShot(topic,id,btn.dataset.direction);else{shot.status=btn.dataset.status;shot.filmed=shot.status==='Снято';}return save();}});
 else if(action==='scene-move'){moveShot(u.draft,id,btn.dataset.direction);u.dirty=true;renderEditor();}
 else if(action==='script-start')startScript();
 else if(action==='quick-create')startQuick(btn.dataset.kind,btn.dataset.day||'');
 else if(action==='day-create')dayActions(btn.dataset.day);
 else if(action==='calendar-task-add')calendarTask(btn.dataset.day);
 else if(action==='calendar-task')calendarTask('',id);
 else if(action==='view')guard(()=>{u.view=btn.dataset.view;if(['scripts','boards'].includes(u.view))u.scenarioView=u.view;render()});
 else if(action==='channel')guard(()=>{u.channel=btn.dataset.channel;render()});
 else if(action==='month-prev'||action==='month-next'||action==='month-today'){const date=new Date((u.calendarMonth||moscowDate().slice(0,7)+'-01')+'T12:00Z');date.setUTCMonth(date.getUTCMonth()+(action==='month-prev'?-1:1));u.calendarMonth=action==='month-today'?moscowDate().slice(0,7)+'-01':date.toISOString().slice(0,10);render();}
 else if(action==='scripts-save'){let next=state;for(const [key,text] of Object.entries(u.scriptEdits)){const topic=structuredClone(plannerState(next).topics.find(t=>t.id===key));if(topic){topic.script=text;next=saveTopic(next,topic);}}await commit(next);u.scriptEdits={};u.dirty=false;render();}
 else if(action==='script-save'){const topic=structuredClone(plannerState(state).topics.find(t=>t.id===id&&t.projId===u.projId));if(!topic)return;topic.script=u.scriptEdits[id]??topic.script;await commit(saveTopic(state,topic),'Текст сценария сохранён');delete u.scriptEdits[id];u.dirty=Boolean(u.draft)||Object.keys(u.scriptEdits).length>0;render();}
 else if(action==='script-delete'){const topic=plannerState(state).topics.find(t=>t.id===id&&t.projId===u.projId);if(!topic)return;confirm('Удалить сценарий «'+topic.title+'»?', 'Будут удалены общий текст и '+topic.scenes.length+' сцен с таймингом и датами съёмки. Тема, публикации и их тексты, файлы и работы проекта сохранятся. Отменить удаление нельзя.',async()=>{const copy=structuredClone(plannerState(state).topics.find(t=>t.id===id&&t.projId===u.projId));copy.script='';copy.scenes=[];await commit(saveTopic(state,copy),'Сценарий удалён, тема и публикации сохранены');delete u.scriptEdits[id];u.dirty=Object.keys(u.scriptEdits).length>0;render();},'Удалить сценарий');}
 else if(action==='script-copy'){const text=u.scriptEdits[id]??plannerState(state).topics.find(t=>t.id===id)?.script;await navigator.clipboard.writeText(text||'');toast('Сценарий скопирован');}
 else if(action==='script-clear'){confirm('Очистить сценарий','Текст будет очищен в карточке. Изменение вступит в силу после сохранения сценариев.',()=>{u.scriptEdits[id]='';u.dirty=true;render();});}
 else if(action==='scope-tab')guard(()=>{u.navScope=btn.dataset.scope;u.folderId='';u.draft=null;render()});
 else if(action==='folder-open')guard(()=>{u.folderId=id;u.draft=null;render()});
 else if(action==='folder-create'||action==='folder-edit'){
 if(u.dirty){guard(()=>[...document.querySelectorAll('[data-action]')].find(x=>x.dataset.action===action&&(!id||x.dataset.id===id))?.click());return;}
 const existing=(plannerState(state).folders||[]).find(f=>f.id===id);if(!owner(u))throw Error('Сначала выберите проект или организацию');
 openDialog(existing?'Название папки':'Создать папку',field('name','Название',existing?.name||'','text',null,true),async data=>{const name=data.name.trim();if(!name)throw Error('Введите название папки');if(scopeFolders(state,u).some(f=>f.id!==id&&f.name.toLowerCase()===name.toLowerCase()))throw Error('Папка с таким названием уже есть');const next=structuredClone(state);next.planner.folders=next.planner.folders||[];const folder={...existing,id:existing?.id||uid(),name,scope:scope(u),ownerId:owner(u)};next.planner.folders=next.planner.folders.filter(f=>f.id!==folder.id);next.planner.folders.push(folder);u.folderId=folder.id;await commit(next)});
 }
 else if(action==='folder-delete')confirm('Удалить папку','Удалить только папку? Материалы сохранятся и станут доступны в «Без папки».',async()=>{const next=structuredClone(state);next.planner.folders=(next.planner.folders||[]).filter(f=>f.id!==id);next.planner.topics.forEach(t=>t.folderIds=(t.folderIds||[]).filter(value=>value!==id));if(u.draft)u.draft.folderIds=(u.draft.folderIds||[]).filter(value=>value!==id);u.folderId='';await commit(next,'Папка удалена, материалы сохранены')});
 else if(action==='org-create')guard(()=>entity('orgs'));
 else if(action==='org-edit')guard(()=>entity('orgs',state.orgs.find(x=>x.id===u.orgId)));
 else if(action==='project-create')guard(()=>entity('projects'));
 else if(action==='project-edit')guard(()=>entity('projects',state.projects.find(x=>x.id===u.projId)));
 else if(action==='archive-list')guard(()=>{u.archive=!u.archive;u.projId='';u.draft=null;selectInitial();render()});
 else if(action==='project-archive')guard(()=>{const project=state.projects.find(x=>x.id===u.projId);confirm(project.archived?'Восстановить проект':'Переместить в архив','Записи проекта сохранятся.',async()=>{const next=structuredClone(state);next.projects.find(x=>x.id===project.id).archived=!project.archived;u.projId='';u.draft=null;await commit(next);selectInitial();render()})});
 else if(action==='topic-create')guard(()=>{if(!u.orgId){entity('orgs');return;}if(!state.projects.some(x=>x.id===u.projId)){entity('projects');return;}u.draft=newTopic(u.projId);u.draft.folderIds=u.folderId?[u.folderId]:[];u.dirty=false;u.editorTab='topic';u.wizard=false;render();scrollTo(0,0)});
 else if(action==='topic-open')openTopic(id,tab||'topic');
 else if(action==='editor-close')closeEditor();
 else if(action==='editor-tab'){u.editorTab=tab;u.wizard=false;u.manualScript=false;renderEditor();$('#material-tab-'+tab)?.focus({preventScroll:true})}
 else if(action==='prep-add'){u.draft.preparation.push({id:uid(),text:'',done:false});u.dirty=true;renderEditor()}
 else if(action==='prep-remove'){u.draft.preparation=u.draft.preparation.filter(x=>x.id!==id);u.dirty=true;renderEditor()}
 else if(action==='scene-add'){u.draft.scenes.push({...newShot(uid()),workIds:[...u.draft.workIds]});u.dirty=true;renderEditor()}
 else if(action==='scene-remove'){confirm('Удалить сцену','Сцена будет удалена после сохранения темы.',()=>{u.draft.scenes=u.draft.scenes.filter(x=>x.id!==id);u.dirty=true;renderEditor()})}
 else if(action==='variant-add'){u.draft.variants.push({id:uid(),platform:'',format:'',text:'',date:u.draft.day||'',ready:'Черновик',link:''});u.dirty=true;renderEditor()}
 else if(action==='variant-remove'){confirm('Удалить вариант публикации','Вариант будет удалён после сохранения темы. Общая тема и другие площадки останутся.',()=>{u.draft.variants=u.draft.variants.filter(x=>x.id!==id);u.dirty=true;renderEditor()})}
 else if(action==='wizard-open'){startQuestions()}
 else if(action==='wizard-close'){stopGeneration();u.wizard=false;renderEditor()}
 else if(action==='script-questions'){guard(()=>{openTopic(id,'script');if(u.draft?.id===id)startQuestions();});}
 else if(action==='script-manual'){u.manualScript=true;renderEditor();$('[name=script]')?.focus();}
 else if(action==='qa-next'){validateQuestions(u.draft,u.wizardStep);u.wizardStep=Math.min(8,u.wizardStep+1);renderEditor();scrollTo(0,0);}
 else if(action==='qa-back'){u.wizardStep=Math.max(0,u.wizardStep-1);renderEditor();scrollTo(0,0);}
 else if(action==='qa-generate'){if(u.aiLoading)return;if(u.aiResult)confirm('Новый предпросмотр?','Новый ответ заменит текущий предпросмотр, включая его ручные правки. Сохранённый сценарий и сцены останутся без изменений.',()=>runGeneration(),'Сгенерировать новый');else await runGeneration();}
 else if(action==='qa-stop'){stopGeneration();u.aiError='Ожидание прекращено. Существующий сценарий не изменён.';renderEditor();}
 else if(action==='qa-accept'){if(!u.aiResult)throw Error('Нет результата AI');u.draft=acceptScenario(u.draft,u.aiResult,u.draft.aiBrief.applyMode);u.dirty=true;u.wizard=false;u.editorTab='script';u.aiResult=null;renderEditor();toast('Результат принят в черновик. Проверьте и сохраните материал.');}
 else if(action==='qa-save-brief'){if(!u.draft.title.trim())throw Error('Укажите тему');const next=saveTopic(state,u.draft);await commit(next,'Вводные сохранены. AI-генерация не выполнялась.');u.dirty=false;renderEditor();}
 else if(action==='works')worksDialog();
 else if(action==='work-create')editWork();
 else if(action==='work-edit')editWork(id);
 else if(action==='week-prev'||action==='week-next'){u.week=addDays(u.week,action==='week-prev'?-7:7);render()}
 else if(action==='week-today'){u.week=moscowDate();render()}
 else if(action==='legacy-shoot'){const x=state.shoots.find(x=>x.id===id);if(!x)return;const topics=plannerState(state).topics.filter(t=>t.projId===u.projId),attached=topics.find(t=>t.legacyShootId===x.id)?.id||'';const options='<option value="">Без темы</option>'+topics.map(t=>'<option value="'+e(t.id)+'" '+(t.id===attached?'selected':'')+'>'+e(t.title)+'</option>').join('');openDialog('Съёмка из прежней версии','<h3>'+e(x.title)+'</h3><p>'+e([x.date,x.time,x.place].filter(Boolean).join(' · '))+'</p><p>'+e(x.desc||'')+'</p><label class="field">Тема для привязки<select name="topicId">'+options+'</select></label><p class="small-note">Можно оставить съёмку отдельно или связать её с темой. Связь используется в таблице и на съёмке.</p><a href="./index.html#cal">Открыть календарь прежней версии</a>',async data=>{const next=structuredClone(state);next.planner=next.planner||{topics:[],works:[]};next.planner.topics=next.planner.topics.map(t=>t.legacyShootId===x.id?({...t,legacyShootId:''}):t);if(data.topicId){const target=next.planner.topics.find(t=>t.id===data.topicId&&t.projId===u.projId);if(!target)throw Error('Тема не найдена');target.legacyShootId=x.id;}await commit(next,'Связь съёмки обновлена');})}
 else if(action==='export')download();
 }catch(err){toast(err.message)}});
document.addEventListener('input',event=>{const el=event.target;if(el.id==='shoot-note'){u.shootNoteDraft=el.value;u.shootNoteDirty=true;const hint=document.querySelector(".shoot-meta .small-note");if(hint){hint.textContent='Есть несохранённая заметка';hint.classList.add('shoot-note-dirty');}return;}if(el.hasAttribute('data-ai-result-script')){if(u.aiResult)u.aiResult.script=el.value;return;}if(el.name?.startsWith('qa-')&&u.draft){const key=el.name.slice(3);if(key==='topic'){u.draft.title=el.value;u.draft.aiBrief.topic=el.value;}else u.draft.aiBrief[key]=el.value;u.dirty=true;if(key!=='applyMode'){u.aiResult=null;u.aiRequestId=null;}if(key==='platform'){u.draft.aiBrief.format='';renderEditor();}return;}if(el.hasAttribute('data-table-date-input')){if(u.tableDate)u.tableDate.value=el.value;return;}if(el.id==='reference-search'){const q=el.value.toLowerCase().trim();let found=0;document.querySelectorAll('[data-search]').forEach(node=>{node.hidden=!node.dataset.search.includes(q);const detail=node.nextElementSibling;if(node.dataset.topicRow&&detail?.dataset.topicDetail===node.dataset.topicRow)detail.hidden=node.hidden||!(u.expandedTopics||[]).includes(node.dataset.topicRow);if(!node.hidden)found++;});$('#reference-search-empty').hidden=found>0||!q;return;}if(el.dataset.inlineScript){u.scriptEdits[el.dataset.inlineScript]=el.value;u.dirty=true;$('.inline-save-note').textContent='Есть несохранённые изменения';return;}if(el.id==='material-search'||el.id==='material-filter'){const q=$('#material-search').value.toLowerCase().trim(),f=$('#material-filter').value;let count=0;document.querySelectorAll('.material-row').forEach(row=>{row.hidden=!row.dataset.search.includes(q)||(f==='script'&&row.dataset.script==='true')||(f==='shoot'&&row.dataset.shoot!=='true')||(f==='approval'&&row.dataset.approval!=='Нужны правки');if(!row.hidden)count++;});$('#search-empty').hidden=count>0;return;}if(!u.draft||!el.closest('#topic-form'))return;const name=el.name;let match;if(name==='folderPick'){moveToFolder(state,u.draft,u,el.value);u.dirty=true;}else if(name?.startsWith('answer-')){u.draft.answers[name.slice(7)]=el.value;if(name==='answer-platform'){u.draft.answers.format='';renderEditor();}u.dirty=true;}
 else if((match=name?.match(/^scene-(title|shots|timeStart|timeEnd|speech|voiceOver|broll|overlay|plan|status|audio|stage|beforeNote|date|deadline|shootId|storyboardFileId)-(.+)$/))){const scene=u.draft.scenes.find(x=>x.id===match[2]);if(scene){scene[match[1]]=el.value;if(match[1]==='status')scene.filmed=el.value==='Снято';u.dirty=true;}}
 else if((match=name?.match(/^variant-(platform|format|text|date|ready|link|duration|videoNotes|photoNotes)-(.+)$/))){const v=u.draft.variants.find(x=>x.id===match[2]);if(v){v[match[1]]=el.value;u.dirty=true;if(match[1]==='platform'){v.format='';v.legacySocial='';renderEditor()}else if(match[1]==='format')renderEditor();}}
 else if(name&&['title','rubric','day','approval','approvalNote','script'].includes(name)){u.draft[name]=el.value;u.dirty=true;}
 else if(el.dataset.prepDeadline){const x=u.draft.preparation.find(x=>x.id===el.dataset.prepDeadline);if(x)x.deadline=el.value;u.dirty=true;}
 else if(el.dataset.prepText){const x=u.draft.preparation.find(x=>x.id===el.dataset.prepText);if(x)x.text=el.value;u.dirty=true;}
 const note=$('.save-note');if(note)note.textContent='Есть несохранённые изменения';});
document.addEventListener('change',async event=>{const el=event.target;try{if(el.hasAttribute('data-table-prep')||el.hasAttribute('data-table-approval')){
  const topic=structuredClone(plannerState(state).topics.find(t=>t.id===el.dataset.topic&&t.projId===u.projId));if(!topic)return;
  if(el.hasAttribute('data-table-prep')){const record=topic.preparation.find(x=>x.id===el.dataset.tablePrep);if(!record)return;record.done=el.checked;}else topic.approval=el.value;
  await commit(saveTopic(state,topic));return;
 }if(el.id==='shoot-date'){const value=el.value;el.value=u.shootDate||'';guard(()=>{u.shootDate=value;u.shootSelected='';u.shootNoteDraft=null;u.shootDetail=false;render()});return;}
 if(el.id==='project-file-upload'){const projId=u.projId,files=[...el.files];if(!files.length)return;if(files.length>30||files.reduce((sum,x)=>sum+x.size,0)>100*1024*1024)throw Error('За один раз — до 30 файлов и 100 МБ');if(files.some(x=>x.size>20*1024*1024))throw Error('Максимум 20 МБ на файл');const records=await Promise.all(files.map(file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({id:uid(),projId,name:file.name,type:file.type,size:file.size,data:reader.result});reader.onerror=()=>reject(Error('Не удалось прочитать файл'));reader.readAsDataURL(file);})));if(!state.projects.some(p=>p.id===projId))throw Error('Проект не найден');const next=structuredClone(state);next.files.push(...records);await commit(next,'Прикреплено файлов: '+records.length);return;}
 if(el.name==='boardTopic'||el.name==='boardFilter'){u[el.name]=el.value;render();return;}
 if(el.id==='add-platform'){const name=el.value;el.value='';if(!platforms[name])return;guard(async()=>{const next=structuredClone(state),project=next.projects.find(p=>p.id===u.projId);if(!project)return;project.contentPlatforms=[...new Set([...(Array.isArray(project.contentPlatforms)?project.contentPlatforms:[]),name])];await commit(next,'Площадка добавлена');});return;}
 if(el.dataset.select){const key=el.dataset.select,value=el.value;if(value==='__add__'){el.value=u[key]||'';if(key==='projId'&&!u.orgId){toast('Сначала добавьте организацию');return;}guard(()=>entity(key==='orgId'?'orgs':'projects'));return;}const apply=()=>{u.draft=null;if(key==='creation-project'){u.projId=value;render();return;}u[key]=value;if(key!=='folderId')u.folderId='';u.channel='';u.boardTopic='';if(key==='orgId'){u.archive=false;u.projId='';selectInitial()}else if(key==='projId'&&value){u.orgId=state.projects.find(x=>x.id===value)?.orgId||u.orgId;}render()};if(u.dirty){el.value=u[key];guard(apply)}else apply()}
 if(u.draft&&el.dataset.qaWork){u.draft.workIds=el.checked?[...new Set([...u.draft.workIds,el.dataset.qaWork])]:u.draft.workIds.filter(x=>x!==el.dataset.qaWork);u.dirty=true;u.aiResult=null;u.aiRequestId=null;}
 if(u.draft&&el.name==='qa-speakerMode')renderEditor();
 if(u.draft&&el.dataset.workId){u.draft.workIds=el.checked?[...new Set([...u.draft.workIds,el.dataset.workId])]:u.draft.workIds.filter(x=>x!==el.dataset.workId);u.dirty=true;}
 if(u.draft&&el.dataset.prepDone){u.draft.preparation.find(x=>x.id===el.dataset.prepDone).done=el.checked;u.dirty=true;}
 if(u.draft&&el.dataset.sceneFlag){u.draft.scenes.find(x=>x.id===el.dataset.id)[el.dataset.sceneFlag]=el.checked;u.dirty=true;renderEditor();}
 if(u.draft&&el.dataset.sceneWork){const scene=u.draft.scenes.find(x=>x.id===el.dataset.id);scene.workIds=el.checked?[...new Set([...(scene.workIds||[]),el.dataset.sceneWork])]:scene.workIds.filter(x=>x!==el.dataset.sceneWork);u.dirty=true;renderEditor();}
 if(u.draft&&/^scene-(date|deadline|storyboardFileId)-/.test(el.name||''))renderEditor();
 if(el.id==='planner-import'){const file=el.files[0];if(!file)return;if(file.size>150*1024*1024)throw Error('Максимум 150 МБ');const imported=importLegacy(normalize(JSON.parse(await file.text()))).state;el.value="";confirm('Импорт плана','Заменить текущие локальные данные содержимым файла? Экспортируйте копию перед заменой.',async()=>{u.draft=null;u.dirty=false;await commit(imported,'Копия импортирована');selectInitial();render()});}
 }catch(err){toast(err.message)}});
document.addEventListener('submit',async event=>{if(event.target.id!=='topic-form')return;event.preventDefault();if(u.wizard)return;const controls=[...event.target.querySelectorAll('button,input,textarea,select')];try{const next=saveTopic(state,u.draft),saved=next.planner.topics.find(x=>x.id===u.draft.id);controls.forEach(x=>x.disabled=true);await commit(next);u.draft=structuredClone(saved);u.dirty=false;render()}catch(err){controls.forEach(x=>x.disabled=false);toast(err.message)}});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&u.tableDate&&!$('#modal').open){event.preventDefault();u.tableDate=null;render();return;}if(event.key==='Escape'&&$('.mobile-nav-open')){$('.reference-shell').classList.remove('mobile-nav-open');$('[data-action=site-menu]')?.setAttribute('aria-expanded','false');return;}if(event.key==='Escape'&&u.draft&&!$('#modal').open){event.preventDefault();u.wizard?(stopGeneration(),u.wizard=false,renderEditor()):closeEditor()}});
document.addEventListener('keydown',event=>{if(event.key!=='Tab'||!u.draft||innerWidth>780||$('#modal').open)return;const nodes=[...$('#topic-form').querySelectorAll('button,input,select,textarea,summary')].filter(x=>!x.disabled&&x.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}});
window.addEventListener('beforeunload',event=>{if(u.dirty||u.tableDate||u.shootNoteDirty){event.preventDefault();event.returnValue='';}});
document.addEventListener('click',event=>{const a=event.target.closest('a[href]');if(a&&(u.dirty||u.shootNoteDirty)){event.preventDefault();guard(()=>{location.href=a.href})}});
(async()=>{try{const result=await openStore(),migrated=importLegacy(result.state);state=migrated.state;if(migrated.changed)await persist(state);try{Object.assign(u,JSON.parse(localStorage.getItem('studio-planner-context')||'{}'));}catch{}selectInitial();render();const topicId=new URLSearchParams(location.search).get('topic');if(topicId){const topic=plannerState(state).topics.find(t=>t.id===topicId);if(topic){u.orgId=state.projects.find(p=>p.id===topic.projId)?.orgId||u.orgId;openTopic(topicId,'scenes');}}}catch(err){$('#planner').innerHTML='<section class="empty-panel"><h1>Не удалось открыть план</h1><p>'+e(err.message)+'</p><a href="./index.html#home">Вернуться на главную</a></section>';}})();

document.addEventListener('keydown',event=>{const node=event.target.closest('[role=tab][data-action=editor-tab]');if(!node||!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const tabs=[...node.closest('[role=tablist]').querySelectorAll('[role=tab]')],i=tabs.indexOf(node),target=event.key==='Home'?0:event.key==='End'?tabs.length-1:(i+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[target].click();});

