import {shootingView} from './shooting-mode.js?v=20261008-single-plan8';
import {projectColor} from './project-colors.js?v=20261008-single-plan8';
import {siteNav,siteHeader} from './workspace-shell.js?v=20261008-single-plan8';
import {contentCalendar} from './content-calendar.js?v=20261008-single-plan8';
import {detailedTable,projectAssets} from './project-assets.js?v=20261008-single-plan8';
import {projectBoards,scriptBoards} from './storyboard.js?v=20261008-single-plan8';
import {escape as e,button as b,badge} from './ui.js?v=20261008-single-plan8';
import {editor} from './planner-view.js?v=20261008-single-plan8';
import {plannerState,moscowDate,addDays,platforms} from './planner-model.js?v=20261008-single-plan8';
import {scopeFolders} from './folder-model.js?v=20261008-single-plan8';
const date=d=>d?new Date(d+'T12:00Z').toLocaleDateString('ru-RU',{day:'numeric',month:'short',timeZone:'Europe/Moscow'}):'Без даты';
const pick=(key,label,id,items,add)=>'<label class="field">'+label+'<select data-select="'+key+'" aria-label="'+label+'"><option value="">Выберите</option>'+items.map(x=>'<option value="'+e(x.id)+'" '+(x.id===id?'selected':'')+'>'+e(x.name)+'</option>').join('')+'<option value="__add__">＋ '+add+'</option></select></label>';
const channel=t=>[...new Set(t.variants.map(v=>v.platform))].filter(Boolean);
const meta=(s,t)=>e(channel(t).join(' · ')||'Площадка не выбрана')+' <span>•</span> '+e(s.rubrics.find(r=>r.id===t.rubric)?.name||'Без рубрики');
const open=(t,label,tab='topic')=>b('topic-open',label,'data-id="'+e(t.id)+'" data-tab="'+tab+'"');
const createMenu=(label='＋ Создать')=>'<details class="create-menu"><summary>'+label+'</summary><div>'+[['topic','Добавить тему','Сценарий и публикации в одной теме'],['shoot','Добавить съёмку без темы','Привязать позже при необходимости'],['post','Добавить публикацию','Выбрать тему и площадку']].map(([kind,title,note])=>b('quick-create','<strong>'+title+'</strong><small>'+note+'</small>','data-kind="'+kind+'"')).join('')+'</div></details>';
export function view(s,u){
 if(u.view==='shooting'&&!u.draft)return shootingView(s,u);
 if(u.draft)return '<main class="material-page"><div id="topic-editor">'+editor(s,u)+'</div></main>';
 const org=s.orgs.find(x=>x.id===u.orgId),projects=s.projects.filter(x=>x.orgId===u.orgId&&Boolean(x.archived)===u.archive),project=projects.find(x=>x.id===u.projId),all=plannerState(s).topics.filter(t=>t.projId===project?.id),folders=scopeFolders(s,u),topics=all.filter(t=>(u.view!=='table'||!u.channel||channel(t).includes(u.channel))&&(!u.folderId||(t.folderIds||[]).includes(u.folderId))),channels=[...new Set([...all.flatMap(channel),...(Array.isArray(project?.contentPlatforms)?project.contentPlatforms.filter(c=>typeof c==='string'):[])])],mode=['calendar','table','links','files','scripts','boards'].includes(u.view)?u.view:'table';
 let h='<div class="reference-shell">'+siteNav(s)+'<div class="reference-workspace">'+siteHeader()+'<main class="reference-main"><div class="reference-title"><div><span class="eyebrow">СТУДИЯ / КОНТЕНТ</span><h1>Контент-план</h1><p>От темы до съёмки и публикации</p></div></div><section class="context-picks">'+pick('orgId','Организация',u.orgId,s.orgs,'Добавить организацию')+pick('projId',u.archive?'Проект · архив':'Проект',u.projId,projects,'Добавить проект')+'<span class="selected-project-color" style="background:'+projectColor(s,u.projId)+'" title="Цвет проекта" aria-label="Цвет проекта"></span><details class="management"><summary>•••</summary><div class="management-menu">'+b('org-create','Добавить организацию')+(org?b('org-edit','Изменить организацию')+b('project-create','Добавить проект')+b('archive-list',u.archive?'Активные проекты':'Архив проектов'):'')+(project?b('project-edit','Изменить проект')+b('project-archive',project.archived?'Восстановить проект':'В архив')+b('works','Работы по проекту с сайта bodr-bo')+b('shoot-open','На съёмке')+b('folder-create','Добавить папку'):'')+'</div></details></section>';
 if(!project)return h+'<div class="empty-panel"><h2>'+(org?'Выберите или добавьте проект':'Начните с организации')+'</h2><p>Выберите «＋ Добавить» в выпадающем списке выше.</p></div></main></div></div>';
 h+='<div class="reference-controls"><div class="view-create-strip"><nav class="reference-tabs" aria-label="Вид контент-плана">'+[['calendar','Календарь','▦'],['table','Таблица','☷'],['scenario-menu','',''],['shooting','На съёмке','▧']].map(([v,label,icon])=>v==='scenario-menu'?scenarioMenu(u,mode):b(v==='works'?'works':'view',icon+' '+label,v==='works'?'':('data-view="'+v+'" aria-pressed="'+(mode===v)+'"'),(mode===v?'active ':'')+(v==='works'?'project-works-tab':''))).join('')+'</nav><details class="planner-more"><summary>Ещё ⌄</summary><div>'+b('works','Работы по проекту с сайта bodr-bo')+b('view','Ссылки','data-view="links" aria-pressed="'+(mode==='links')+'"')+b('view','Файлы','data-view="files" aria-pressed="'+(mode==='files')+'"')+'</div></details></div>'+(mode!=='table'?'<input id="reference-search" type="search" aria-label="Поиск тем" placeholder="Поиск тем…">':'')+'</div>';
 if(folders.length)h+='<div class="optional-folder"><label>Папка <select data-select="folderId"><option value="">Все темы проекта</option>'+folders.map(f=>'<option value="'+e(f.id)+'" '+(f.id===u.folderId?'selected':'')+'>'+e(f.name)+'</option>').join('')+'</select></label>'+b('folder-create','＋ Папка')+'</div>';
 h+='<section class="reference-surface" id="plan-list">';
 if(mode==='boards')h+=projectBoards(s,u);
 if(mode==='scripts'){
 h+='<div class="surface-heading"><div><h2>Сценарии</h2><p>Тема → текст сценария → сцены с таймингом → публикации</p></div>'+'<div class="scripts-heading-actions">'+b('script-start','＋ Создать сценарий')+b('scripts-save','Сохранить сценарии','','primary')+'</div>'+'</div>';
 h+='<details class="scenario-help"><summary>Как устроен сценарий?</summary><p><strong>Тема</strong> — о чём видео. <strong>Сценарий</strong> — общий текст и замысел. <strong>Раскадровка</strong> — что показываем в каждой сцене, тайминг, речь ведущего и закадровый голос.</p><p>Например: «Ремонт корпуса» → вступление, процесс, результат → сцены 00:00–00:10 и далее. Дата съёмки — день в календаре, тайминг — секунды внутри видео.</p><p>Создайте сценарий по теме, затем проверьте черновик и поправьте текст и сцены через «Редактировать». Мастер передаёт вводные AI только при настроенном OpenAI API. Если AI не подключён, можно сохранить ответы или писать вручную. Текст и сцены редактируются отдельно, изменения текста не переписывают раскадровку.</p></details>';for(const ready of [true,false]){const group=topics.filter(t=>Boolean((u.scriptEdits?.[t.id]??t.script)?.trim())===ready);h+='<div class="script-group"><h3><span class="group-marker '+(!ready?'pending':'')+'">'+(ready?'✓':'○')+'</span> '+(ready?'Есть текст сценария':'Без сценария')+' <span class="count">'+group.length+'</span></h3>'+group.map(t=>'<article class="reference-script" data-search="'+e([t.title,...channel(t)].join(' ').toLowerCase())+'"><div class="script-card-heading"><div><h3>'+e(t.title)+'</h3><p>'+date(t.variants.map(v=>v.date).filter(Boolean).sort()[0]||t.day)+' <span>•</span> '+meta(s,t)+'</p></div>'+badge(t.approval||'Не отправлено','#7161df')+'</div>'+((Boolean((u.scriptEdits?.[t.id]??t.script)?.trim())?'<textarea data-inline-script="'+e(t.id)+'" aria-label="Сценарий: '+e(t.title)+'">'+e(u.scriptEdits?.[t.id]??t.script)+'</textarea>':'<div class="qa-empty"><p>Пока нет сценария. Ответьте на вопросы о теме, фактах и кадрах — это вводные для AI.</p>'+b('script-questions','Создать с AI · вопросы','data-id="'+e(t.id)+'"','primary')+'</div>')+'<div class="script-actions">'+b('script-save','Сохранить','data-id="'+e(t.id)+'"','primary')+open(t,'Редактировать','script')+b('shoot-open','На съёмке','data-topic="'+e(t.id)+'"')+b('script-copy','Копировать','data-id="'+e(t.id)+'"')+b('script-delete','Удалить сценарий','data-id="'+e(t.id)+'"','subtle')+'</div>')+'<details class="scenario-scenes"><summary>Раскадровка · '+t.scenes.length+' сцен</summary>'+scriptBoards(s,t)+'</details></article>').join('')+(!group.length?'<p class="group-empty">'+(ready?'Текстов сценариев пока нет.':'Все темы со сценариями.')+'</p>':'')+'</div>';}
 h+='<p class="inline-save-note" role="status">'+(u.dirty?'Есть несохранённые изменения':'Текст можно исправить прямо в карточке и сохранить. Для работы со сценами откройте «Редактировать».')+'</p>';
 }
 if(mode==='table')h+=detailedTable(s,topics,createMenu,u,[...new Set([...Object.keys(platforms),...channels])]);
 if(mode==='calendar')h+=contentCalendar(s,u,topics);
 if(mode==='links'||mode==='files')h+=projectAssets(s,u,mode);
 if(!all.length&&['scripts','table'].includes(mode)&&!(mode==='table'&&s.shoots.some(x=>x.projId===u.projId)))h+='<div class="empty-state"><h2>Здесь пока нет тем</h2><p>Добавьте тему и подготовьте сценарий, сцены и публикации.</p>'+(mode==='table'?'':createMenu())+'</div>';
 return h+'</section><p id="reference-search-empty" hidden>По вашему запросу ничего не найдено.</p></main></div></div>';
}

function scenarioMenu(u,mode){const selected=['scripts','boards'].includes(mode)?mode:u.scenarioView,label=selected==='scripts'?'Сценарии':selected==='boards'?'Раскадровки':'Сценарии и раскадровки';return '<details class="scenario-view-menu '+(['scripts','boards'].includes(mode)?'active':'')+'"><summary aria-label="'+label+' · выбрать раздел">'+label+' <span aria-hidden="true">⌄</span></summary><div>'+b('view','▤ Сценарии','data-view="scripts" aria-pressed="'+(mode==='scripts')+'"')+b('view','▧ Раскадровки','data-view="boards" aria-pressed="'+(mode==='boards')+'"')+'</div></details>';}
