import {validDate} from './planner-model.js?v=20261008-single-plan8';
import {sceneTemplate} from './storyboard.js?v=20261008-single-plan8';
import {seconds,timecode,validateSequence,timingLabel} from './scene-timing.js?v=20261008-single-plan8';
import {escape as e} from './ui.js?v=20261008-single-plan8';
export const speakers=[['host','Ведущий в кадре'],['voiceover','Закадровый голос'],['silent','Без речи']];
export function planScenes(brief,makeId,works=[]){if(!validDate(brief.shootDate)||!validDate(brief.deadline))throw Error('Проверьте даты съёмок');if(brief.shootDate&&brief.deadline&&brief.shootDate>brief.deadline)throw Error('Дата съёмки позже крайнего срока');if(brief.speakerMode&&!speakers.some(([value])=>value===brief.speakerMode))throw Error('Проверьте режим речи');const scenes=sceneTemplate(brief.durationSeconds,makeId),mode=brief.speakerMode||'host',topic=(brief.topic||'').trim(),facts=(brief.facts||'').trim(),work=works.filter(w=>(brief.workIds||[]).includes(w.id));const spoken=['Сегодня показываем: '+(topic||'[уточнить тему]')+'.',brief.problem?brief.problem:'[Кратко объяснить задачу и исходное состояние.]',facts?'По предоставленным данным: '+facts:'[Добавить только подтверждённые факты о процессе.]','[Сформулировать подтверждённый итог и следующий шаг.]'];for(const [i,x] of scenes.entries()){x.speakerMode=mode;x.speech=mode==='host'?spoken[i]:'';x.voiceOver=mode==='voiceover'?spoken[i]:'';x.speechDraft=mode!=='silent';x.timingApproximate=true;x.date=brief.shootDate||'';x.deadline=brief.deadline||'';x.workIds=work.map(w=>w.id);x.shots=(mode==='host'?x.shots:x.shots.replace('ведущего и ','').replace(' и ведущего в финальном кадре',' в финальном кадре'))+(i===2&&brief.work?' Работа по вашим данным: '+brief.work:'')+(i===2&&brief.mustCapture?'\nОбязательные кадры: '+brief.mustCapture:'')+(i===1&&brief.available?'\nДоступно снять: '+brief.available:'')+(work.length?'\nРаботы: '+work.map(w=>w.name).join(', '):'');x.broll=i===2?'[Уточнить дополнительные детали и перебивки]':'';x.overlay=(mode==='silent'?spoken[i]:'[Уточнить титры]');x.audio='[Уточнить звук и музыку]';if(work.some(w=>w.irreversible)&&i===1){x.beforeWork=true;x.beforeNote='Проверить, какие исходные состояния нужно снять до необратимой работы.';}}validateSequence(scenes);return scenes;}
export function scenarioText(brief,scenes){return 'ЧЕРНОВИК ДЛЯ ПРОВЕРКИ · ОРИЕНТИРОВОЧНЫЙ ТАЙМИНГ\nТема: '+brief.topic+'\n'+[brief.platform,brief.format].filter(Boolean).join(' · ')+'\n\n'+scenes.map((x,i)=>(i+1)+'. '+x.title+'\nВ кадре: '+x.shots+'\n'+(x.speech?'Ведущий (черновик): '+x.speech:x.voiceOver?'Закадровый голос (черновик): '+x.voiceOver:'Без речи · титры: '+x.overlay)).join('\n\n');}
export function planPreview(scenes){return '<p class="small-note">Начальный план по вашим данным. Тайминг ориентировочный, реплики — черновик для проверки. Текст в квадратных скобках нужно уточнить.</p>'+scenes.map((x,i)=>'<div class="scene-preview-row"><strong>'+(i+1)+'. '+e(timingLabel(x))+'</strong><span>'+e(x.title)+'</span><p>'+e(x.shots)+'</p><p>'+e(x.speech||x.voiceOver||'Без речи · '+x.overlay)+'</p></div>').join('');}
export function appendPlan(existing,generated){const end=Math.max(0,...existing.map(x=>seconds(x.timeEnd)||0));return [...structuredClone(existing),...generated.map(x=>({...x,timeStart:timecode(end+seconds(x.timeStart)),timeEnd:timecode(end+seconds(x.timeEnd))}))];}
