import {escape as e,button as b,pretty} from './ui.js?v=20261008-topic-only7';
import {icon} from './icons.js?v=20261008-topic-only7';
import {plannerState} from './planner-model.js?v=20261008-topic-only7';
import {shotStatus} from './storyboard.js?v=20261008-topic-only7';
import {siteNav} from './workspace-shell.js?v=20261008-topic-only7';
export function shootRecords(s,u){return plannerState(s).topics.filter(t=>t.projId===u.projId&&(!u.shootTopic||t.id===u.shootTopic)).flatMap(t=>t.scenes.map((scene,index)=>({topic:t,scene,index,key:encodeURIComponent(t.id)+'~'+encodeURIComponent(scene.id)}))).filter(r=>!u.shootDate||r.scene.date===u.shootDate);}
export function selectedShot(s,u){const rows=shootRecords(s,u);return rows.find(r=>r.key===u.shootSelected)||rows.find(r=>u.shootFilter!=='remaining'||shotStatus(r.scene)!=='Снято');}
function reference(s,r,small=false){const f=s.files.find(f=>f.id===r.scene.storyboardFileId&&f.projId===r.topic.projId);return f&&/^data:image\/(png|jpeg|webp|gif|avif);base64,/.test(f.data||'')?'<img src="'+e(f.data)+'" alt="'+e(f.name)+'" '+(small?'loading="lazy"':'')+'>':'<span class="no-reference">'+icon('camera')+(small?'':'<span>Референс не прикреплён</span>')+'</span>';}
function status(r){const value=shotStatus(r.scene);return '<span class="shoot-state '+(value==='Снято'?'done':r.scene.beforeWork?'critical':'')+'">'+icon(value==='Снято'?'check':'clock')+e(value==='Снято'?'Снято':r.scene.beforeWork?'Важно':value==='Переснять'?'Переснять':'Осталось')+'</span>';}
export function shootingView(s,u){
 const rows=shootRecords(s,u),selected=selectedShot(s,u),shown=rows.filter(r=>u.shootFilter!=='remaining'||shotStatus(r.scene)!=='Снято'),done=rows.filter(r=>shotStatus(r.scene)==='Снято').length,left=rows.length-done,critical=rows.filter(r=>r.scene.beforeWork&&shotStatus(r.scene)!=='Снято').length,p=s.projects.find(x=>x.id===u.projId),org=s.orgs.find(x=>x.id===p?.orgId),sc=selected?.scene,t=selected?.topic;
 const pct=rows.length?Math.round(done/rows.length*100):0;
 let h='<div class="reference-shell shooting-shell '+(u.shootDetail?'shoot-detail-open':'')+'">'+siteNav(s)+'<main class="shoot-workspace"><div class="shoot-top"><div class="site-crumb">'+b('site-menu',icon('menu'),'aria-label="Открыть меню разделов"','site-menu-button')+e(org?.name||'Организация')+' <span>/</span> '+e(p?.name||'Проект')+'</div>'+b('shoot-back','← Вернуться к плану')+'</div><div class="shoot-heading"><div><h1>На съёмке</h1><div class="shoot-date-picker"><label>Дата <input id="shoot-date" type="date" value="'+e(u.shootDate||'')+'"></label><span>'+(u.shootDate?pretty(u.shootDate):'Все даты · включая кадры без даты')+'</span></div>'+(u.shootTopic?'<p class="small-note">Сценарий: '+e(t?.title||plannerState(s).topics.find(t=>t.id===u.shootTopic)?.title||'')+' '+b('shoot-scope','Все сценарии проекта')+'</p>':'')+'</div><section class="shoot-progress" aria-label="Прогресс съёмки"><div><strong>Снято '+done+' из '+rows.length+'</strong><div class="progress-line"><progress value="'+done+'" max="'+(rows.length||1)+'" aria-label="Снято кадров"></progress><span>'+pct+'%</span></div></div><div><span>Осталось</span><strong class="progress-number">'+left+'</strong></div><div class="critical-count">'+critical+' '+(critical%100>=11&&critical%100<=14?'важных кадров':critical%10===1?'важный кадр':critical%10>=2&&critical%10<=4?'важных кадра':'важных кадров')+'</div></section></div><div class="shoot-grid"><section class="shoot-panel shoot-list"><header><h2>Кадры '+(u.shootDate?'на дату':'проекта')+'</h2><div class="tabs">'+b('shoot-filter','Все','data-filter="all"',u.shootFilter!=='remaining'?'active':'')+b('shoot-filter','Осталось','data-filter="remaining"',u.shootFilter==='remaining'?'active':'')+'</div></header>'+shown.map(r=>b('shoot-select','<span class="shot-thumb">'+reference(s,r,true)+'</span><span class="shoot-row-body"><strong>'+String(r.index+1).padStart(2,'0')+' · '+e(r.scene.title||'Кадр без названия')+'</strong><small>'+e(r.scene.plan||'План не выбран')+' · '+e(r.topic.title)+'</small><small>'+pretty(r.scene.date)+'</small></span>'+status(r),'data-key="'+e(r.key)+'"','shoot-row '+(r.key===selected?.key?'selected':''))).join('')+(!shown.length?'<div class="empty"><h3>'+(rows.length?'Все кадры сняты':'Кадров пока нет')+'</h3><p>'+(u.shootDate?'Измените дату или очистите её, чтобы увидеть остальные кадры.':'Добавьте сцены в раскадровке материала.')+'</p>'+b('shoot-back','К плану')+'</div>':'')+'</section>';
 if(selected){h+='<section class="shoot-panel shoot-scene">'+b('shoot-list','← К списку кадров','','mobile-scene-back')+'<header><h2>'+e(sc.title||'Кадр без названия')+'</h2><span class="badge">Кадр '+String(selected.index+1).padStart(2,'0')+'</span></header><div class="shoot-reference">'+reference(s,selected)+'</div><div class="scene-chips"><span>'+icon('camera')+e(sc.plan||'План не выбран')+'</span><span>'+icon('clock')+'В ролике: '+e(sc.timeStart&&sc.timeEnd?sc.timeStart+'–'+sc.timeEnd:'тайминг не задан')+'</span></div><div class="shoot-copy"><h3>Что снять</h3><p>'+e(sc.shots||'Действие пока не описано')+'</p><h3>'+(sc.speakerMode==='voiceover'?'Закадровый голос':sc.speakerMode==='silent'?'Без речи':'Речь ведущего')+'</h3><p>'+e(sc.speakerMode==='silent'?'Сцена без речи':sc.speakerMode==='voiceover'?(sc.voiceOver||'Текст не задан'):(sc.speech||'Реплика не задана'))+'</p>'+(sc.speakerMode!=='voiceover'&&sc.voiceOver?'<h3>Закадровый текст</h3><p>'+e(sc.voiceOver)+'</p>':'')+(sc.broll?'<h3>Перебивки</h3><p>'+e(sc.broll)+'</p>':'')+(sc.audio?'<h3>Звук / музыка</h3><p>'+e(sc.audio)+'</p>':'')+'</div><div class="shoot-status-actions">'+b('shoot-status',icon('check')+' Снято','data-status="Снято" aria-pressed="'+(shotStatus(sc)==='Снято')+'"','primary')+b('shoot-status',icon('redo')+' Нужен пересъём','data-status="Переснять" aria-pressed="'+(shotStatus(sc)==='Переснять')+'"')+'</div>'+b('shoot-next','Следующий неснятый кадр →','','shoot-next')+'</section><aside class="shoot-meta">'+(sc.beforeWork?'<section class="shoot-panel shoot-critical"><h3>Снять до начала работы</h3><p>'+e(sc.beforeNote||'Зафиксируйте состояние до начала работы.')+'</p>'+status(selected)+'</section>':'')+'<section class="shoot-panel"><h2>Съёмка</h2><dl><div><dt>Этап</dt><dd>'+e(sc.stage||'Не выбран')+'</dd></div><div><dt>Дата</dt><dd>'+pretty(sc.date)+'</dd></div><div><dt>Крайний срок</dt><dd>'+pretty(sc.deadline)+'</dd></div><div><dt>Сценарий</dt><dd>'+e(t.title)+'</dd></div><div><dt>Статус</dt><dd>'+e(shotStatus(sc))+'</dd></div></dl>'+b('topic-open','Редактировать сцену','data-id="'+e(t.id)+'" data-tab="scenes"')+'</section><section class="shoot-panel"><h2>Заметка к кадру</h2><label class="field"><span class="sr-only">Заметка к кадру</span><textarea id="shoot-note" placeholder="Добавить заметку…" maxlength="10000">'+e(u.shootNoteDraft??sc.shootNote??'')+'</textarea></label>'+b('shoot-note-save',icon('save')+' Сохранить заметку','','shoot-save-note')+'<small class="small-note">'+(u.shootNoteDirty?'Есть несохранённая заметка':'Заметка хранится в этом материале')+'</small></section></aside>';}
 h+='</div>';
 if(t){const timeline=t.scenes.map((scene,index)=>({scene,index,topic:t,key:encodeURIComponent(t.id)+'~'+encodeURIComponent(scene.id)}));h+='<section class="shoot-panel shoot-timeline"><h2>Таймлайн сценария</h2><div>'+timeline.map(r=>b('shoot-select','<strong>'+String(r.index+1).padStart(2,'0')+'</strong><span class="shot-thumb">'+reference(s,r,true)+'</span><span><strong>'+e(r.scene.title||'Без названия')+'</strong><small>'+e(r.scene.plan||'План не выбран')+'</small><small>'+e(r.scene.timeStart||'Без тайминга')+'</small></span>','data-key="'+e(r.key)+'"','timeline-card '+(r.key===selected.key?'selected':''))).join('')+'</div><p class="small-note">Тайминг внутри ролика. Чтобы открыть кадры вне выбранной даты, очистите фильтр даты.</p></section>';}
 return h+'</main></div>';
}

