import {seconds,timecode,timingLabel} from './scene-timing.js?v=20261008-single-plan8';
import {escape as e,field,button as b,badge} from './ui.js?v=20261008-single-plan8';
import {plannerState} from './planner-model.js?v=20261008-single-plan8';
export const shotStatuses=['Запланирован','Снято','Переснять'];
export const shotStatus=x=>shotStatuses.includes(x.status)?x.status:x.filmed?'Снято':'Запланирован';
export function newShot(id){return {id,title:'',shots:'',plan:'',timeStart:'',timeEnd:'',speech:'',voiceOver:'',broll:'',overlay:'',audio:'',stage:'',status:'Запланирован',date:'',deadline:'',workIds:[],filmed:false,beforeWork:false,beforeNote:'',storyboardFileId:''};}
export function sceneTemplate(duration,makeId){const n=Number(duration);if(!Number.isInteger(n)||n<10||n>3600)throw Error('Длительность — целое число от 10 до 3600 секунд');const edges=[0,Math.round(n*.1),Math.round(n*.3),Math.round(n*.85),n];const titles=['Начало: привлечь внимание','Контекст: что показываем','Основная часть: процесс и детали','Финал: результат и следующий шаг'];const hints=['Показать ведущего и главный объект видео.','Показать исходное состояние и детали, о которых говорит ведущий.','Снять ключевые действия по порядку. Чередовать общий план и детали.','Показать итог и ведущего в финальном кадре.'];return titles.map((title,i)=>({...newShot(makeId()),title,shots:hints[i],plan:i===2?'Деталь':'Средний',timeStart:timecode(edges[i]),timeEnd:timecode(edges[i+1]),template:true}));}
function sceneBreakdown(x){return '<div class="scene-breakdown"><div><span>В кадре</span><p>'+e(x.shots||'Опишите действие и движение камеры')+'</p></div><div><span>Речь ведущего · черновик для проверки</span><p>'+e(x.speech||(x.speakerMode==='silent'?'Без речи':'Не задано'))+'</p></div><div><span>Закадровый голос · черновик для проверки</span><p>'+e(x.voiceOver||(x.speakerMode==='silent'?'Без речи':'Не задано'))+'</p></div><div><span>Дополнительные кадры</span><p>'+e(x.broll||'Не задано')+'</p></div><div><span>Звук / музыка</span><p>'+e(x.audio||'Не задано')+'</p></div><div><span>Титры / монтаж</span><p>'+e(x.overlay||'Не задано')+'</p></div></div>';}
const date=d=>new Date(d+'T12:00Z').toLocaleDateString('ru-RU',{day:'numeric',month:'short',year:'numeric',timeZone:'Europe/Moscow'});
const dates=x=>[x.date?'Съёмка: '+date(x.date):'',x.deadline?'Крайний срок: '+date(x.deadline):''].filter(Boolean).join(' · ')||'Без даты';
const select=(name,label,value,values)=>field(name,label,value,'text',values);
export function shotFields(s,t,x,prefix='scene-'){
 const works=plannerState(s).works.filter(w=>w.projId===t.projId),name=k=>prefix+k+'-'+x.id;
 return field(name('title'),'Что показать',x.title,'text',null,true)+'<div class="field-pair scene-time-fields">'+field(name('timeStart'),'Начало · мин:сек',x.timeStart||'')+field(name('timeEnd'),'Конец · мин:сек',x.timeEnd||'')+'</div><p class="small-note">Ориентировочный тайминг внутри видео, например 00:05 — 00:12. Речь — черновик для проверки.</p>'+field(name('speech'),'Речь ведущего',x.speech||'','textarea')+field(name('voiceOver'),'Закадровый текст',x.voiceOver||'','textarea')+field(name('broll'),'Дополнительные кадры / перебивки',x.broll||'','textarea')+field(name('shots'),'Действие в кадре / последовательность',x.shots||'','textarea')+'<div class="field-pair">'+select(name('plan'),'План',x.plan||'',[['','Не выбран'],...['Общий','Средний','Крупный','Деталь'].map(v=>[v,v])])+select(name('status'),'Статус',shotStatus(x),shotStatuses.map(v=>[v,v]))+'</div>'+field(name('audio'),'Звук / музыка (прежние реплики сохранены)',x.audio||'','textarea')+field(name('overlay'),'Титры / монтажные заметки',x.overlay||'','textarea')+'<div class="field-pair">'+field(name('date'),'Примерная дата съёмки',x.date||'','date')+field(name('deadline'),'Крайний срок',x.deadline||'','date')+'</div><details class="shot-extra"><summary>Работы, этап и референс</summary>'+select(name('stage'),'Этап',x.stage||'',[['','Не выбран'],...['До','В процессе','После'].map(v=>[v,v])])+works.map(w=>'<label class="checkbox-line"><input type="checkbox" data-scene-work="'+e(w.id)+'" data-id="'+e(x.id)+'" '+((x.workIds||[]).includes(w.id)?'checked':'')+'>'+e(w.name)+(w.startDate?' · '+e(w.startDate):'')+'</label>').join('')+(!works.length?'<p class="small-note">Работы ещё не добавлены в проект.</p>':'')+'<label class="checkbox-line"><input type="checkbox" data-scene-flag="beforeWork" data-id="'+e(x.id)+'" '+(x.beforeWork?'checked':'')+'>Снять до начала работы</label>'+field(name('beforeNote'),'Почему нельзя пропустить кадр',x.beforeNote||'','textarea')+select(name('storyboardFileId'),'Референс из файлов проекта',x.storyboardFileId||'',[['','Без изображения'],...s.files.filter(f=>f.projId===t.projId&&f.type?.startsWith('image/')).map(f=>[f.id,f.name])])+select(name('shootId'),'Связанная съёмка',x.shootId||'',[['','Без связи'],...s.shoots.filter(z=>!z.projId||z.projId===t.projId).map(z=>[z.id,z.title])])+'<p class="small-note">Даты работ вводятся вручную. Расписание цеха не подключено.</p></details>'+shotImage(s,x);
}
function shotImage(s,x){const f=s.files.find(f=>f.id===x.storyboardFileId);return f&&/^data:image\/(png|jpeg|webp|gif|avif);base64,/.test(f.data||'')?'<img class="storyboard-image" src="'+e(f.data)+'" alt="'+e(f.name)+'">':'';}
export function storyboardEditor(s,t){return '<div class="script-heading"><h3>Раскадровка сценария</h3>'+b('scene-add','＋ Кадр')+'</div><p class="small-note">Порядок кадров меняется стрелками. Сценарий и кадры сохраняются вместе.</p>'+t.scenes.map((x,i)=>'<div class="shot-card"><div class="shot-order"><span>'+String(i+1).padStart(2,'0')+'</span>'+b('scene-move','↑','data-id="'+e(x.id)+'" data-direction="-1" '+(!i?'disabled':'')+' aria-label="Кадр выше"')+b('scene-move','↓','data-id="'+e(x.id)+'" data-direction="1" '+(i===t.scenes.length-1?'disabled':'')+' aria-label="Кадр ниже"')+'</div><details class="shot-detail" '+(!x.title?'open':'')+'><summary><strong>'+e(x.title||'Новый кадр')+'</strong><span>'+e(shotStatus(x))+'</span><small>'+e([timingLabel(x),x.plan,x.stage,dates(x)].filter(Boolean).join(' · '))+'</small>'+(x.beforeWork&&shotStatus(x)!=='Снято'?'<small class="urgent">Снять до работы · '+e(x.beforeNote||'уточните причину')+'</small>':'')+'</summary><div>'+shotFields(s,t,x)+b('scene-remove','Удалить кадр','data-id="'+e(x.id)+'"','danger')+'</div></details></div>').join('')+(!t.scenes.length?'<div class="group-empty">Раскадровка пока пуста. Добавьте первый кадр вручную.</div>':'');}
export function projectBoards(s,u){
 const topics=plannerState(s).topics.filter(t=>t.projId===u.projId),rows=topics.filter(t=>!u.boardTopic||t.id===u.boardTopic).flatMap(t=>t.scenes.map((x,i)=>({t,x,i}))).filter(({x})=>u.boardFilter==='unshot'?shotStatus(x)!=='Снято':u.boardFilter==='critical'?x.beforeWork&&shotStatus(x)!=='Снято':true);
 return '<div class="surface-heading"><div><h2>Кадры проекта</h2><p>Единая раскадровка всех сценариев · '+rows.length+' кадров</p></div>'+b('board-add','＋ Кадр','','primary')+'</div><div class="board-filters">'+field('boardTopic','Сценарий',u.boardTopic||'','text',[['','Все сценарии'],...topics.map(t=>[t.id,t.title])])+field('boardFilter','Показать',u.boardFilter||'all','text',[['all','Все кадры'],['unshot','Ещё не снятые'],['critical','Снять до работы']])+'</div>'+rows.map(({t,x,i})=>'<article class="project-shot" data-search="'+e([t.title,x.title,x.shots,x.speech,x.audio].join(' ').toLowerCase())+'"><div class="shot-order"><span>'+String(i+1).padStart(2,'0')+'</span>'+b('board-move','↑','data-id="'+e(x.id)+'" data-topic="'+e(t.id)+'" data-direction="-1" '+(!i?'disabled':'')+' aria-label="Кадр выше"')+b('board-move','↓','data-id="'+e(x.id)+'" data-topic="'+e(t.id)+'" data-direction="1" '+(i===t.scenes.length-1?'disabled':'')+' aria-label="Кадр ниже"')+'</div><div class="project-shot-info">'+b('board-edit',e(x.title),'data-id="'+e(x.id)+'" data-topic="'+e(t.id)+'"','row-open')+'<p>'+e(x.shots||'Действие пока не описано')+'</p><small>'+e([timingLabel(x),x.plan,x.stage,dates(x)].filter(Boolean).join(' · '))+'</small>'+(x.beforeWork&&shotStatus(x)!=='Снято'?'<p class="urgent">До начала работы: '+e(x.beforeNote||'причина не указана')+'</p>':'')+'<div>'+b('topic-open','Сценарий: '+e(t.title),'data-id="'+e(t.id)+'" data-tab="script"','shot-topic')+'</div></div><div class="shot-actions">'+badge(shotStatus(x),shotStatus(x)==='Снято'?'#28745b':'#7161df')+b('board-status',shotStatus(x)==='Снято'?'Переснять':'Отметить снятым','data-id="'+e(x.id)+'" data-topic="'+e(t.id)+'" data-status="'+(shotStatus(x)==='Снято'?'Переснять':'Снято')+'"')+b('board-delete','Удалить','data-id="'+e(x.id)+'" data-topic="'+e(t.id)+'"','subtle')+'</div></article>').join('')+(!rows.length?'<p class="group-empty">Нет кадров по выбранным условиям. Добавьте кадр к теме — сценарий может быть ещё не написан.</p>':'');
}

export function scriptBoards(s,t){return '<section class="inline-storyboard"><div class="inline-board-heading"><h4>Сцены и раскадровка <span>'+t.scenes.length+' кадров</span></h4>'+b('board-template','Составить раскадровку','data-topic="'+e(t.id)+'"')+b('board-add','＋ Добавить кадр','data-topic="'+e(t.id)+'"')+'</div><p class="small-note">Ориентировочный хронометраж: '+timecode(Math.max(0,...t.scenes.map(x=>seconds(x.timeEnd)||0)))+'. Реплики — черновик для проверки.</p>'+t.scenes.map((x,i)=>'<article class="inline-board-row"><div class="shot-order"><span>'+String(i+1).padStart(2,'0')+'</span>'+b('board-move','↑','data-topic="'+e(t.id)+'" data-id="'+e(x.id)+'" data-direction="-1" '+(!i?'disabled':'')+' aria-label="Кадр выше"')+b('board-move','↓','data-topic="'+e(t.id)+'" data-id="'+e(x.id)+'" data-direction="1" '+(i===t.scenes.length-1?'disabled':'')+' aria-label="Кадр ниже"')+'</div><div class="inline-board-content"><details open><summary><strong>'+e(x.title)+'</strong><small>'+e([timingLabel(x),x.plan,x.stage,dates(x)].filter(Boolean).join(' · '))+'</small></summary>'+sceneBreakdown(x)+shotImage(s,x)+'</details>'+(x.beforeWork&&shotStatus(x)!=='Снято'?'<p class="urgent">Снять до работы: '+e(x.beforeNote||'причина не указана')+'</p>':'')+'<div class="inline-board-actions">'+badge(shotStatus(x),shotStatus(x)==='Снято'?'#28745b':'#7561df')+b('scene-duration','Длительность','data-topic="'+e(t.id)+'" data-id="'+e(x.id)+'"')+b('board-edit','Изменить','data-topic="'+e(t.id)+'" data-id="'+e(x.id)+'"')+b('board-status',shotStatus(x)==='Снято'?'Переснять':'Снято','data-topic="'+e(t.id)+'" data-id="'+e(x.id)+'" data-status="'+(shotStatus(x)==='Снято'?'Переснять':'Снято')+'"')+b('board-delete','Удалить','data-topic="'+e(t.id)+'" data-id="'+e(x.id)+'"','subtle')+'</div></div></article>').join('')+(!t.scenes.length?'<p class="group-empty">Кадров пока нет. Добавьте первый кадр — что показать, действие и план.</p>':'')+'</section>';}
