import {escape as e,button as b,badge} from './ui.js?v=20261008-topic-only7';
import {icon} from './icons.js?v=20261008-topic-only7';
import {topicMetrics,topicNumber,shortDate} from './topic-metrics.js?v=20261008-topic-only7';
import {nextAction,linkedShoots,ungroupedShoots} from './table-records.js?v=20261008-topic-only7';
import {approval} from './planner-model.js?v=20261008-topic-only7';
import {shotStatus} from './storyboard.js?v=20261008-topic-only7';

const open=(t,label,tab='topic',cls='')=>b('topic-open',label,'data-id="'+e(t.id)+'" data-tab="'+tab+'"',cls);
const fullDate=value=>value?shortDate(value)+' '+value.slice(0,4)+' г.':'Не назначена';
const detailId=t=>'topic-detail-'+encodeURIComponent(t.id);
const searchable=(s,t)=>e([t.title,...t.variants.map(x=>x.platform),s.rubrics.find(x=>x.id===t.rubric)?.name||''].join(' ').toLowerCase());
function platformPicker(u,channels){return '<details class="table-platform-menu"><summary aria-label="Выбрать соцсеть для таблицы"><span>'+e(u.channel||'Выбрать соцсеть')+'</span><span aria-hidden="true">⌄</span></summary><div class="table-platform-options">'+b('channel','Все темы','data-channel="" aria-pressed="'+(!u.channel)+'"')+channels.map(c=>b('channel',e(c),'data-channel="'+e(c)+'" aria-pressed="'+(u.channel===c)+'"')).join('')+'</div></details>';}
function dateControl(t,record,group,key,label,u){
 const topic=t?.id||'',data='data-topic="'+e(topic)+'" data-id="'+e(record.id)+'" data-group="'+group+'" data-field="'+key+'"',edit=u.tableDate,editing=edit&&edit.topic===topic&&edit.id===record.id&&edit.group===group&&edit.field===key;
 return '<div class="table-date-control">'+(editing?'<div class="table-date-editor"><label>'+e(label)+'<input type="date" data-table-date-input aria-label="'+e(label)+'" value="'+e(edit.value)+'"></label><div>'+b('table-date-save','Сохранить','','primary')+b('table-date-cancel','Отмена')+'</div><p class="table-date-error" role="alert">'+e(edit.error||'')+'</p></div>':b('table-date-edit',e(label)+': <strong>'+fullDate(record[key])+'</strong>',data,'table-date-button'))+'</div>';
}
function summaryDate(t,ref,label,overdue=false){return ref?b('table-date-edit',e(label)+(overdue?' · Просрочено':''),'data-topic="'+e(t.id)+'" data-id="'+e(ref.id)+'" data-group="'+ref.group+'" data-field="'+ref.field+'"','topic-date '+(overdue?'overdue':'')):'<span class="topic-date">'+e(label)+'</span>';}
function indicator(t,label,tab,type,complete=false){return open(t,icon(type)+'<span>'+e(label)+'</span><svg class="indicator-arrow" viewBox="0 0 24 24" aria-hidden="true"><path d="m9 5 7 7-7 7"/></svg>',tab,'topic-indicator '+(complete?'complete':''));}
function nextStep(t,m){
 const x=nextAction(t);
 if(x.done)return '<span class="topic-finished">'+icon('check')+e(x.label)+'</span>';
 const shoot=x.tab==='scenes'&&(x.critical||x.label==='Отметить снятые кадры');
 return (shoot?b('shoot-open',e(x.critical?x.label:'Продолжить съёмку'),'data-topic="'+e(t.id)+'"','primary topic-next-action'):open(t,e(x.label),x.tab,'primary topic-next-action'))+(x.tab==='topic'&&t.approval==='На согласовании'?'<small class="topic-note">Согласование отмечается вручную</small>':'');
}
function summaryRow(s,t,u){
 const m=topicMetrics(s,t,u.channel),expanded=(u.expandedTopics||[]).includes(t.id),number=topicNumber(s,u.projId,t.id),critical=m.critical[0],pubLabel=m.publicationsComplete?'Опубликовано '+m.published+' из '+m.variants.length:'Готовы '+m.ready+' из '+m.variants.length;
 return '<tr class="topic-summary" data-topic-row="'+e(t.id)+'" data-search="'+searchable(s,t)+'"><td data-label="№ / Тема"><div class="topic-identity">'+b('table-topic-toggle','<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 5 7 7-7 7"/></svg>','data-id="'+e(t.id)+'" aria-label="'+(expanded?'Свернуть':'Раскрыть')+' подробности темы '+number+'" aria-expanded="'+expanded+'" aria-controls="'+detailId(t)+'"','topic-disclosure')+'<span class="topic-number">'+number+'</span>'+open(t,e(t.title),'topic','topic-name')+'</div></td><td data-label="Сценарий">'+indicator(t,m.scriptLabel,'script','content')+'</td><td data-label="Съёмка">'+indicator(t,m.sceneCount?'Снято '+m.filmed+' из '+m.sceneCount:'Кадры не добавлены','scenes','camera',m.shootComplete&&Boolean(m.sceneCount))+(m.shootComplete?'<span class="topic-date">Съёмка завершена</span>':summaryDate(t,m.shootRef,m.shootRef?.value?shortDate(m.shootRef.value):'Дата не назначена',m.shootOverdue))+(m.overdueDeadline?summaryDate(t,m.overdueDeadline,'Крайний срок: '+shortDate(m.overdueDeadline.value),true):'')+(m.undatedShoots&&m.shootRef?.value?'<small class="topic-note">Без даты: '+m.undatedShoots+'</small>':'')+(critical?'<small class="topic-critical">'+icon('clock')+e(critical.beforeNote?.trim()||'Снять до начала работы')+(m.critical.length>1?' · '+m.critical.length+' кадра':'')+'</small>':'')+'</td><td data-label="Публикации">'+indicator(t,m.variants.length?pubLabel:'Публикации не добавлены','variants','external',m.publicationsComplete)+(m.publicationsComplete?'<span class="topic-date">Все варианты опубликованы</span>':summaryDate(t,m.publicationRef,m.publicationRef?.value?'Выход: '+shortDate(m.publicationRef.value):'Выход не назначен',m.publicationOverdue))+(m.published&&!m.publicationsComplete?'<small class="topic-note">Опубликовано '+m.published+' из '+m.variants.length+'</small>':'')+(m.undatedPublications&&m.publicationRef?.value?'<small class="topic-note">Без даты выхода: '+m.undatedPublications+'</small>':'')+'</td><td data-label="Следующий шаг"><div class="plan-next-step">'+nextStep(t,m)+'</div></td></tr>';
}
function sceneDetails(s,t,u){return '<section class="topic-detail-section"><header><h3>Кадры и съёмки</h3>'+open(t,'Редактировать','scenes')+'</header>'+t.scenes.map((x,i)=>'<article class="plan-record" data-scene-record="'+e(x.id)+'"><strong>'+(i+1)+'. '+e(x.title||'Кадр без названия')+'</strong>'+badge(shotStatus(x),shotStatus(x)==='Снято'?'#28745b':'#7561df')+(x.timeStart?'<small class="topic-note">В ролике: '+e(x.timeStart)+'–'+e(x.timeEnd||'не задано')+'</small>':'')+(x.beforeWork&&shotStatus(x)!=='Снято'?'<p class="topic-critical">'+e(x.beforeNote||'Снять до начала работы')+'</p>':'')+dateControl(t,x,'scenes','date','Дата съёмки',u)+dateControl(t,x,'scenes','deadline','Крайний срок съёмки',u)+b('board-edit','Изменить сцену','data-topic="'+e(t.id)+'" data-id="'+e(x.id)+'"','detail-action')+'</article>').join('')+linkedShoots(s,t).map(x=>'<article class="plan-record"><strong>'+e(x.title||'Съёмка')+'</strong><small class="topic-note">Связана с календарём</small>'+dateControl(t,x,'shoots','date','Дата съёмки',u)+b('legacy-shoot','Открыть съёмку','data-id="'+e(x.id)+'"','detail-action')+'</article>').join('')+(!t.scenes.length&&!linkedShoots(s,t).length?'<p class="topic-note">Кадры пока не добавлены.</p>':'')+(t.scenes.length?b('shoot-open','На съёмке','data-topic="'+e(t.id)+'"','detail-action'):'')+'</section>';}
function publicationDetails(t,u){return '<section class="topic-detail-section"><header><h3>Публикации по площадкам</h3>'+open(t,'Редактировать','variants')+'</header>'+t.variants.map(v=>'<article class="plan-record compact-publication" data-variant-record="'+e(v.id)+'"><strong>'+e(v.platform)+' · '+e(v.format)+'</strong>'+badge(v.ready||'Черновик',v.ready==='Опубликовано'?'#28745b':v.ready==='Готово'?'#397a9d':'#7561df')+dateControl(t,v,'variants','date','Дата публикации',u)+'</article>').join('')+(!t.variants.length?'<p class="topic-note">Варианты публикаций пока не добавлены.</p>':'')+'</section>';}
function preparationDetails(t,u){return '<section class="topic-detail-section"><header><h3>Подготовка и согласование</h3>'+open(t,'Редактировать')+'</header><p class="topic-note">Выполнено '+t.preparation.filter(x=>x.done).length+' из '+t.preparation.length+'</p>'+t.preparation.map(x=>'<article class="plan-record"><label class="table-prep-check"><input type="checkbox" data-table-prep="'+e(x.id)+'" data-topic="'+e(t.id)+'" '+(x.done?'checked':'')+'><span>'+e(x.text)+'</span></label>'+dateControl(t,x,'preparation','deadline','Дедлайн подготовки',u)+'</article>').join('')+'<label class="field topic-approval">Согласование<select data-table-approval data-topic="'+e(t.id)+'">'+approval.map(v=>'<option '+(t.approval===v?'selected':'')+'>'+e(v)+'</option>').join('')+'</select></label>'+(t.approvalNote?'<p class="topic-note">'+e(t.approvalNote)+'</p>':'')+'<small class="topic-note">Чек-лист и согласование сохраняются сразу. Согласование отмечается вручную.</small></section>';}
function detailRow(s,t,u){return '<tr class="topic-expansion" data-topic-detail="'+e(t.id)+'" id="'+detailId(t)+'" '+((u.expandedTopics||[]).includes(t.id)?'':'hidden')+'><td colspan="5"><div class="topic-expanded-heading"><strong>'+e(t.title)+'</strong>'+open(t,'Открыть тему')+'</div><div class="topic-detail-grid">'+sceneDetails(s,t,u)+publicationDetails(t,u)+preparationDetails(t,u)+'</div></td></tr>';}
function standalone(s,u){const list=!u.channel&&!u.folderId?ungroupedShoots(s,u.projId):[];return list.length?'<details class="unlinked-shoots" data-plan-detail="unlinked-shoots"><summary>Съёмки без темы · '+list.length+'</summary><p class="topic-note">Эти записи календаря не привязаны к темам. Они сохраняются отдельно.</p>'+list.map(x=>'<article class="plan-record" data-ungrouped-shoot="'+e(x.id)+'" data-search="'+e((x.title||'Съёмка').toLowerCase())+'"><strong>'+e(x.title)+'</strong>'+dateControl(null,x,'shoots','date','Дата съёмки',u)+b('legacy-shoot','Открыть съёмку','data-id="'+e(x.id)+'"','detail-action')+'</article>').join('')+'</details>':'';}
export function topicTable(s,topics,createMenu,u={},channels=[]){return '<div class="surface-heading plan-heading topic-table-heading"><div><h2>План публикаций и съёмок</h2><p>Темы выбранного проекта</p></div><div class="topic-table-tools"><input id="reference-search" type="search" aria-label="Поиск тем" placeholder="Поиск тем…">'+createMenu('＋ Добавить')+platformPicker(u,channels)+'</div></div><div class="plan-table-wrap"><table class="plan-table detail-plan-table compact-plan topic-plan"><thead><tr><th>№ / Тема</th><th>Сценарий</th><th>Съёмка</th><th>Публикации</th><th>Следующий шаг</th></tr></thead><tbody>'+topics.map(t=>summaryRow(s,t,u)+detailRow(s,t,u)).join('')+(!topics.length?'<tr class="compact-empty"><td colspan="5">'+(u.channel?'Для '+e(u.channel)+' пока нет тем. Выберите другую соцсеть или «Все темы».':'Добавьте первую тему кнопкой «Добавить».')+'</td></tr>':'')+'</tbody></table></div><p class="topic-table-footnote">Даты съёмки и выхода редактируются по нажатию. Стрелка рядом с номером раскрывает подробности.</p>'+standalone(s,u)+'<details class="scenario-help topic-table-help"><summary>Как пользоваться таблицей?</summary><p>Одна строка — одна тема выбранного проекта. Номер отражает её место в порядке тем проекта; поиск и выбор соцсети не меняют номер. Название темы открывает полную карточку, стрелка — кадры, публикации, подготовку и согласование под строкой.</p><p>Нажмите показатель, чтобы редактировать сценарий, кадры или публикации этой темы. «Есть текст» не означает, что сценарий готов. Готовые и опубликованные варианты считаются отдельно. Кнопка последнего столбца ведёт к текущему незавершённому действию.</p><p>Даты — календарные дни, тайминг кадра — секунды внутри ролика. Просрочка учитывает дату по Москве. Сохранение, отмена и Escape меняют только выбранную дату. Публикации и согласование отмечаются вручную.</p></details>';}

