import {icon,brand} from './icons.js?v=20261008-topic-only7';
import {generalShoots,projectColor,projectName} from './project-colors.js?v=20261008-topic-only7';
import {dateKey} from './model.js?v=20261008-topic-only7';
import {escape as e,money,pretty,button as b,empty,badge,link} from './ui.js?v=20261008-topic-only7';
export const sections=[['home','◈','Главная'],['cal','▦','Календарь'],['content','▤','Контент-план'],['tasks','✓','Задачи'],['gear','▣','Снаряжение'],['portfolio','▧','Портфолио'],['account','◎','Аккаунт'],['settings','⚙','Настройки']];
const edit=(type,id)=>b('edit','Изменить','data-type="'+type+'" data-id="'+e(id)+'"')+b('delete','×','data-type="'+type+'" data-id="'+e(id)+'" aria-label="Удалить"','danger');
const add=(type,text='Добавить')=>b('add','＋ '+text,'data-type="'+type+'"','primary');
const card=(title,body,action='')=>'<section class="card"><div class="card-header"><h2>'+title+'</h2>'+action+'</div>'+body+'</section>';
const stat=(label,value,note,section)=>b('navigate','<div class="stat-top"><span>'+label+'</span><span>↗</span></div><div class="stat-value">'+value+'</div><div class="stat-note">'+note+'</div>','data-section="'+section+'"','stat');
const opts=(list,value,placeholder)=>'<option value="">'+placeholder+'</option>'+list.map(x=>'<option value="'+e(x.id)+'" '+(x.id===value?'selected':'')+'>'+e((x.emoji||'')+' '+x.name)+'</option>').join('');
export function shell(s,u,body){
 const title=sections.find(x=>x[0]===u.section)?.[2]||'Обзор';
 return '<div class="shell"><aside class="sidebar" id="sidebar">'+b('menu-close','×','aria-label="Закрыть меню"','general-nav-close')+'<div class="brand">'+brand()+'</div><div class="nav-label">РАБОЧЕЕ ПРОСТРАНСТВО</div><nav class="nav" aria-label="Основная навигация">'+sections.map(([id,icon,label])=>b('navigate','<span class="nav-icon">'+navIcon(id)+'</span><span>'+label+'</span>','data-section="'+id+'" '+(u.section===id?'aria-current="page"':''),u.section===id?'active':'')).join('')+'</nav><div class="side-bottom"><div class="storage-info"><span class="dot"></span>Локальное пространство<br>Данные на этом устройстве</div><div class="user"><div class="avatar">'+e((s.profile.name||'С').slice(0,1).toUpperCase())+'</div><div><strong>'+e(s.profile.name||'Ваша студия')+'</strong><small>'+e(s.profile.org||'Личный аккаунт')+'</small></div></div></div></aside>'+b('menu-close','Закрыть меню','aria-label="Закрыть меню"','general-nav-shade')+'<div class="workspace"><header class="topbar"><div class="top-actions">'+b('menu','☰','aria-label="Открыть меню"','mobile-menu')+'<span class="crumb">Рабочее пространство <span> / </span> <b>'+title+'</b></span></div><div class="top-actions"><span class="top-date">'+new Date().toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'})+'</span>'+b('assistant','✧ Помощник')+'</div></header><main class="main"><div class="page-heading"><div><span class="eyebrow">СТУДИЯ / '+title.toUpperCase()+'</span><h1>'+title+'</h1><p class="subtitle">'+subtitles[u.section]+'</p></div>'+({home:add('shoots','Съёмка'),cal:add('shoots','Съёмка'),tasks:add('tasks','Задача'),gear:add('gear','Снаряжение'),portfolio:add('portfolio','Работа'),account:add('finances','Операция')}[u.section]||'')+'</div>'+body+'</main></div></div>';
}
const subtitles={home:'Всё важное для вашей творческой работы.',cal:'Планируйте съёмки и держите расписание под рукой.',content:'От первой идеи до опубликованного материала.',tasks:'Освободите голову — соберите дела в одном месте.',gear:'Ваш комплект и его стоимость.',portfolio:'Коллекция работ, которыми хочется делиться.',account:'Профиль студии и прозрачный учёт финансов.',settings:'Настройте пространство под свой ритм.'};
export function shootList(list,s={projects:[]}){return list.length?list.map(x=>'<div class="list-row project-shoot-row" style="--project-color:'+projectColor(s,x.projId)+'"><div class="date-tile">'+e(x.date?.slice(8)||'—')+'<small>'+e(x.date?new Date(x.date+'T12:00').toLocaleDateString('ru-RU',{month:'short'}):'')+'</small></div><div class="list-main"><small class="calendar-project-label">'+e(projectName(s,x.projId))+'</small><strong>'+e(x.title)+'</strong><small>'+e([pretty(x.date),x.time,x.place].filter(Boolean).join(' · '))+'</small></div><div class="row-actions">'+(x.source==='planner'?b('planner-shoot','Открыть сцену','data-id="'+e(x.topicId)+'"'):edit('shoots',x.id))+'</div></div>').join(''):empty('Пока нет съёмок','Запланируйте съёмку — она появится в календаре.')}
function taskRows(list){return list.length?list.map(x=>'<div class="list-row '+(x.done?'done':'')+'"><input type="checkbox" data-toggle-task="'+e(x.id)+'" aria-label="Выполнено: '+e(x.text)+'" '+(x.done?'checked':'')+'><div class="list-main"><strong>'+e(x.text)+'</strong><small>'+e(x.date?'До '+pretty(x.date):'Без срока')+'</small></div>'+badge({low:'Низкий',medium:'Средний',high:'Высокий'}[x.priority]||'Средний',{low:'#699176',medium:'#b48c46',high:'#b96559'}[x.priority])+'<div class="row-actions">'+edit('tasks',x.id)+'</div></div>').join(''):empty('Задач пока нет')}
export function monthGrid(s,date,mini=false,posts=null){
 const y=date.getFullYear(),m=date.getMonth(),first=new Date(y,m,1),offset=(first.getDay()+6)%7,today=dateKey();
 let h='<div class="'+(mini?'mini':'')+'"><div style="display:grid;grid-template-columns:repeat(7,1fr)">'+['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=>'<div class="weekday">'+x+'</div>').join('')+'</div><div class="calendar-grid">';
 for(let i=0;i<42;i++){
 const d=new Date(y,m,i-offset+1),key=dateKey(d),items=(posts||generalShoots(s)).filter(x=>x.date===key);
 h+=b(mini?'calendar-date':posts?'post-day':'day','<span class="day-num">'+d.getDate()+'</span>'+items.slice(0,mini?1:3).map(x=>'<span class="event project-calendar-event" style="--project-color:'+projectColor(s,x.projId)+'"><small>'+e(projectName(s,x.projId))+'</small>'+e((x.time?x.time+' ':'')+x.title)+'</span>').join('')+(!mini&&items.length>3?'<small>＋'+(items.length-3)+'</small>':''),'data-date="'+key+'" aria-label="'+e(d.toLocaleDateString('ru-RU'))+'; записей: '+items.length+'"','day '+(key===today?'today ':'')+(d.getMonth()!==m?'outside ':'')+([0,6].includes(d.getDay())?'weekend':''));
 }
 return h+'</div></div>';
}
export function home(s,u){
 const upcoming=generalShoots(s).filter(x=>x.date>=dateKey()).sort((a,b)=>(a.date+(a.time||'')).localeCompare(b.date+(b.time||'')));
 const active=s.tasks.filter(x=>!x.done);
 return '<div class="hero"><div><span class="eyebrow">МЕСТО ДЛЯ ВАШИХ ИДЕЙ</span><h2>Рабочий день<br>в одном месте.</h2><p>'+e(s.profile.name||'Ваша студия')+', сегодня у вас '+generalShoots(s).filter(x=>x.date===dateKey()).length+' съёмок и '+active.length+' активных задач.</p>'+b('navigate','Открыть календарь ↗','data-section="cal"','primary')+'</div><div class="home-summary"><strong>'+upcoming.length+'</strong><span>предстоящих съёмок</span><strong>'+active.length+'</strong><span>задач в работе</span></div></div><div class="stats">'+stat('Предстоящие съёмки',upcoming.length,'Ваше расписание','cal')+stat('Активные задачи',active.length,'Фокус на главном','tasks')+stat('Материалы в плане',s.posts.length,s.projects.filter(x=>!x.archived).length+' активных проектов','content')+stat('Работы в портфолио',s.portfolio.length,s.gear.length+' позиций снаряжения','portfolio')+'</div><div class="grid-two"><div>'+card('Ближайшие съёмки',shootList(upcoming.slice(0,4),s),b('navigate','Все съёмки ↗','data-section="cal"'))+card('В фокусе',taskRows(active.slice(0,4)),b('navigate','Все задачи ↗','data-section="tasks"'))+'</div><div>'+card(new Date().toLocaleDateString('ru-RU',{month:'long',year:'numeric'}),monthGrid(s,new Date(),true))+card('Быстрый старт','<p class="subtitle" style="margin-bottom:18px">Соберите рабочее пространство для нового проекта.</p><div class="toolbar">'+add('orgs','Организация')+b('navigate','Контент-план ↗','data-section="content"')+'</div>')+'</div></div>';
}
export function calendar(s,u){
 const d=new Date(u.date+'T12:00:00'),mode=u.calMode,shoots=generalShoots(s);
 let title=d.toLocaleDateString('ru-RU',{month:'long',year:'numeric'}),body='';
 if(mode==='month')body=monthGrid(s,d);
 if(mode==='day'){title=d.toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'});body=shootList(shoots.filter(x=>x.date===u.date).sort((a,b)=>(a.time||'').localeCompare(b.time||'')),s)+b('add','＋ Съёмка на этот день','data-type="shoots" data-date="'+u.date+'"','primary')}
 if(mode==='week'){
 const start=new Date(d);start.setDate(d.getDate()-((d.getDay()+6)%7));const end=new Date(start);end.setDate(start.getDate()+6);
 title=pretty(dateKey(start))+' — '+pretty(dateKey(end));body='<div class="week-grid">';
 for(let i=0;i<7;i++){const day=new Date(start);day.setDate(start.getDate()+i);const key=dateKey(day);body+='<div class="week-day"><h3>'+e(day.toLocaleDateString('ru-RU',{weekday:'short',day:'numeric',month:'short'}))+'</h3>'+shoots.filter(x=>x.date===key).sort((a,b)=>(a.time||'').localeCompare(b.time||'')).map(x=>b(x.source==='planner'?'planner-shoot':'edit','<small>'+e(projectName(s,x.projId))+'</small>'+e((x.time||'')+' '+x.title),'style="--project-color:'+projectColor(s,x.projId)+'" data-type="shoots" data-id="'+e(x.source==='planner'?x.topicId:x.id)+'"','week-event project-calendar-event')).join('')+b('day','＋','data-date="'+key+'" aria-label="Съёмки '+key+'"')+'</div>'}body+='</div>';
 }
 if(mode==='year'){title=d.getFullYear()+' год';body='<div class="year-grid">'+Array.from({length:12},(_,m)=>'<div class="month-card"><h3>'+new Date(d.getFullYear(),m,1).toLocaleDateString('ru-RU',{month:'long'})+'</h3>'+monthGrid(s,new Date(d.getFullYear(),m,1),true)+'</div>').join('')+'</div>'}
 if(mode==='decade'){const start=Math.floor(d.getFullYear()/10)*10;title=start+' — '+(start+9);body='<div class="decade-grid">'+Array.from({length:10},(_,i)=>b('calendar-year',start+i,'data-year="'+(start+i)+'"')).join('')+'</div>'}
 const ids=[...new Set(shoots.map(x=>x.projId).filter(Boolean))],legend='<div class="project-calendar-legend">'+ids.map(id=>'<span><i style="background:'+projectColor(s,id)+'"></i>'+e(projectName(s,id))+'</span>').join('')+'</div>';return '<section class="card"><div class="calendar-head"><div class="calendar-nav">'+b('cal-prev','‹','aria-label="Предыдущий период"')+'<h2>'+e(title)+'</h2>'+b('cal-next','›','aria-label="Следующий период"')+'</div><div class="toolbar" style="margin:0">'+b('cal-today','Сегодня')+'<select data-control="calMode" aria-label="Режим календаря" style="width:auto">'+[['month','Месяц'],['week','Неделя'],['day','День'],['year','Год'],['decade','10 лет']].map(([v,t])=>'<option value="'+v+'" '+(mode===v?'selected':'')+'>'+t+'</option>').join('')+'</select></div></div>'+legend+body+'</section>';
}
export function content(s,u){
 const orgs=s.orgs,projects=s.projects.filter(x=>x.orgId===u.orgId&&Boolean(x.archived)===u.archive),p=projects.find(x=>x.id===u.projId);
 let h=card('Организации и проекты','<div class="toolbar"><select class="grow" data-control="orgId" aria-label="Организация">'+opts(orgs,u.orgId,'Выберите организацию')+'</select>'+add('orgs','Организация')+(u.orgId?'<div class="row-actions">'+edit('orgs',u.orgId)+'</div>':'')+'</div><div class="toolbar"><select class="grow" data-control="projId" aria-label="Проект">'+opts(projects,u.projId,u.archive?'Архивные проекты':'Выберите проект')+'</select>'+add('projects','Проект')+b('toggle-archive',u.archive?'Активные проекты':'Архив')+(p?b('archive',p.archived?'Восстановить':'В архив','data-id="'+e(p.id)+'"')+'<div class="row-actions">'+edit('projects',p.id)+'</div>':'')+'</div>');
 if(!p)return h+card('Контент вашего проекта',empty(orgs.length?'Выберите или создайте проект':'Начните с организации','У каждого проекта будут свои посты, ссылки и файлы.'));
 const posts=s.posts.filter(x=>x.projId===p.id),query=u.query.toLowerCase();
 const filtered=posts.filter(x=>(x.title+' '+(x.text||'')).toLowerCase().includes(query)&&(!u.postStatus||x.status===u.postStatus));
 h+='<div class="toolbar"><div class="tabs">'+[['cal','Календарь'],['table','Таблица'],['links','Ссылки'],['files','Файлы']].map(([v,t])=>b('post-tab',t,'data-tab="'+v+'"',u.postTab===v?'active':'')).join('')+'</div><span class="grow"></span>'+add('posts','Пост')+'</div>';
 if(['cal','table'].includes(u.postTab)){
 h+='<div class="toolbar"><input data-control="query" value="'+e(u.query)+'" placeholder="Поиск материалов…" aria-label="Поиск материалов"><select data-control="postStatus" style="width:auto" aria-label="Статус">'+opts(s.statuses,u.postStatus,'Все статусы')+'</select><span class="muted">'+filtered.length+' материалов</span></div>';
 if(u.postTab==='cal'){
 const d=new Date(u.postDate+'T12:00:00');h+=card('План публикаций','<div class="calendar-head"><div class="calendar-nav">'+b('post-prev','‹','aria-label="Предыдущий месяц"')+'<h2>'+d.toLocaleDateString('ru-RU',{month:'long',year:'numeric'})+'</h2>'+b('post-next','›','aria-label="Следующий месяц"')+'</div>'+b('post-today','Текущий месяц')+'</div>'+monthGrid(s,d,false,filtered));
 }else h+=card('Материалы',filtered.length?'<div class="table-wrap"><table><thead><tr><th>Дата</th><th>Материал</th><th>Соцсеть</th><th>Рубрика</th><th>Статус</th><th></th></tr></thead><tbody>'+filtered.slice().sort((a,b)=>(a.date||'').localeCompare(b.date||'')).map(x=>{const social=s.socials.find(v=>v.id===x.social),rubric=s.rubrics.find(v=>v.id===x.rubric),status=s.statuses.find(v=>v.id===x.status);return '<tr><td>'+pretty(x.date)+'</td><td><strong>'+e(x.title)+'</strong></td><td>'+e(social?.name||'—')+'</td><td>'+badge(rubric?.name||'Без рубрики',rubric?.color)+'</td><td>'+badge(status?.name||'Без статуса',status?.color)+'</td><td><div class="row-actions">'+edit('posts',x.id)+'</div></td></tr>'}).join('')+'</tbody></table></div>':empty('Материалов пока нет'));
 }
 if(u.postTab==='links'){const rows=s.links.filter(x=>x.projId===p.id);h+=card('Ссылки проекта',rows.length?rows.map(x=>'<div class="list-row"><div class="list-main"><strong>'+e(x.name)+'</strong><small>'+e(x.url)+'</small></div>'+link(x.url)+'<div class="row-actions">'+edit('links',x.id)+'</div></div>').join(''):empty('Ссылок пока нет'),add('links','Ссылка'))}
 if(u.postTab==='files'){const rows=s.files.filter(x=>x.projId===p.id);h+=card('Файлы проекта','<div class="notice">Вложения сохраняются на этом устройстве. Максимальный размер одного файла — 20 МБ.</div>'+(rows.length?rows.map(x=>'<div class="list-row"><span>▤</span><div class="list-main"><strong>'+e(x.name)+'</strong><small>'+e(x.type||'Файл')+'</small></div>'+b('view-file','Просмотр','data-id="'+e(x.id)+'"')+'<div class="row-actions">'+b('delete','×','data-type="files" data-id="'+e(x.id)+'" aria-label="Удалить файл"')+'</div></div>').join(''):empty('Файлов пока нет')),'<label class="file-label">＋ Загрузить<input type="file" id="upload-files" multiple></label>')}
 return h;
}
export function tasks(s,u){
 const rows=s.tasks.filter(x=>(u.taskFilter==='all'||(u.taskFilter==='done'?x.done:!x.done))&&x.text.toLowerCase().includes(u.query.toLowerCase()));
 return '<div class="toolbar"><div class="tabs">'+[['all','Все'],['active','Активные'],['done','Выполненные']].map(([v,t])=>b('task-filter',t,'data-filter="'+v+'"',u.taskFilter===v?'active':'')).join('')+'</div><input data-control="query" value="'+e(u.query)+'" placeholder="Найти задачу…" aria-label="Поиск задач"></div>'+card('Список задач',taskRows(rows));
}
export function gear(s){
 const total=s.gear.reduce((sum,x)=>sum+x.qty*x.price,0);
 return '<div class="stats">'+stat('Стоимость комплекта',money(total),'Все позиции снаряжения','gear')+stat('Единиц оборудования',s.gear.reduce((sum,x)=>sum+x.qty,0),'В вашем комплекте','gear')+'</div>'+card('Оборудование',s.gear.length?'<div class="table-wrap"><table class="gear-table"><thead><tr><th>Название</th><th>Категория</th><th>Количество</th><th>Цена</th><th>Стоимость</th><th></th></tr></thead><tbody>'+s.gear.map(x=>'<tr><td data-label="Название"><strong>'+e(x.name)+'</strong></td><td data-label="Категория">'+e(s.gearCats.find(c=>c.id===x.catId)?.name||'Без категории')+'</td><td data-label="Количество">'+x.qty+'</td><td data-label="Цена">'+money(x.price)+'</td><td data-label="Стоимость">'+money(x.qty*x.price)+'</td><td><div class="row-actions">'+edit('gear',x.id)+'</div></td></tr>').join('')+'</tbody></table></div>':empty('Соберите свой комплект'));
}
export function portfolio(s,u){
 const rows=s.portfolio.filter(x=>!u.portCat||x.catId===u.portCat);
 return '<div class="toolbar"><select data-control="portCat" style="max-width:260px" aria-label="Категория портфолио">'+opts(s.portCats,u.portCat,'Все категории')+'</select></div>'+(rows.length?'<div class="portfolio-grid">'+rows.map(x=>{const cat=s.portCats.find(c=>c.id===x.catId);return '<article class="portfolio-item"><div class="portfolio-art" aria-hidden="true">'+e(cat?.emoji||'◈')+'</div><div class="portfolio-info"><h3>'+e(x.name)+'</h3>'+badge(cat?.name||'Без категории')+'<div class="list-row">'+link(x.link,'Смотреть работу ↗')+'<div class="row-actions">'+edit('portfolio',x.id)+'</div></div></div></article>'}).join('')+'</div>':card('Работы',empty('Создайте своё портфолио','Добавьте название, категорию и ссылку на работу.')));
}
export function account(s){
 const income=s.finances.filter(x=>x.type==='income').reduce((sum,x)=>sum+x.amount,0),expense=s.finances.filter(x=>x.type==='expense').reduce((sum,x)=>sum+x.amount,0);
 return '<div class="stats">'+stat('Доходы',money(income),'Все поступления','account')+stat('Расходы',money(expense),'Все затраты','account')+stat('Баланс',money(income-expense),'Доходы минус расходы','account')+'</div><div class="grid-two"><div>'+card('История операций',s.finances.length?s.finances.slice().reverse().map(x=>'<div class="list-row"><span class="badge" style="--tag:'+(x.type==='income'?'#28745b':'#b96559')+'">'+(x.type==='income'?'↙ Доход':'↗ Расход')+'</span><div class="list-main"><strong>'+e(x.desc||'Операция')+'</strong><small>'+pretty(x.date)+'</small></div><strong>'+money(x.amount)+'</strong><div class="row-actions">'+edit('finances',x.id)+'</div></div>').join(''):empty('Операций пока нет'))+'</div><div>'+card('Профиль студии','<div class="list-row"><div class="avatar">'+e((s.profile.name||'С')[0])+'</div><div class="list-main"><strong>'+e(s.profile.name||'Ваша студия')+'</strong><small>'+e(s.profile.org||'Личный аккаунт')+'</small></div></div><p class="subtitle">'+e(s.profile.email||'Email не указан')+'</p>',b('profile','Изменить'))+'</div></div>';
}
export function settings(s){
 let h='<div class="settings-grid">'+card('Внешний вид','<p class="subtitle" style="margin-bottom:20px">Тема, цвет, размер текста и ширина меню.</p>'+b('appearance','Настроить оформление'));
 h+=card('Данные и резервные копии','<p class="subtitle" style="margin-bottom:20px">JSON-копия включает записи и все вложенные файлы.</p><div class="toolbar">'+b('export','↓ Экспорт')+'<label class="file-label">↑ Импорт<input type="file" id="import-data" accept=".json,application/json"></label></div><div class="toolbar">'+b('diagnose','Диагностика')+b('repair','Восстановить связи')+b('reset','Очистить данные','','danger')+'</div>');
 for(const [key,title] of [['rubrics','Рубрики постов'],['socials','Соцсети'],['statuses','Статусы публикаций'],['gearCats','Категории снаряжения'],['portCats','Категории портфолио']]){
 h+=card(title,s[key].length?s[key].map(x=>'<div class="dictionary-row"><span>'+e((x.emoji||'')+' '+x.name)+'</span>'+(x.color?badge('Цвет',x.color):'')+'<div class="row-actions">'+edit(key,x.id)+'</div></div>').join(''):empty('Справочник пуст'),add(key));
 }
 return h+'</div>';
}

const navIcon=key=>icon(key);

